### ISSUE TITLE
Problem with get implied sequence

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#111]
Parts BBa_K174003 and BBa_S04199 when instantiated seem to produce incorrect top-level sequences.  There is perhaps some problem with get implied sequences.  However, it should not actually determine an implied sequence, since the sequence should be known already for the sub-part.

**Comment by michael13162** [comment]
When you say "it should not actually determine an implied sequence, since the sequence should be known already for the sub-part", what exactly do you mean?  The instantiated top-level sequence initially shown is what is specified by the part.  However, getImplied specifies a shorter sequence, so the tail base pairs are replaced with 'N's.

**Comment by cjmyers** [comment]
I think it was a different issue on my end. Can ignore for now

Chris

**Comment by cjmyers** [comment]
The problem appears to have been caused by these lines of code in populateComponents:

			// TODO: what was this for?
			/*
			if (canvasCD != comp) {
				addCD(comp);
			}
			*/

I don’t recall why I added them.  They are removed for now, and the problem has gone away.

**Comment by michael13162** [comment]
I think this may be a remnant of the old populateComponents() method and had something to do with updating the rootCD in some special case... but I also don't remember.  It may no longer be needed with your changes, though.  I guess we can take a closer look if a bug pops up in the future.

**Comment by cjmyers** [comment]
It looks like it accidentally got captured into the “if (completelyAnnotated)” clause.  I think it likely should come after this one and before the Component based sorting, if it is still needed, so I’ve moved it down there.  It is still commented out though.
