### ISSUE TITLE
J107030, getting lots of N's

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#116]
why?

**Comment by cjmyers** [comment]
I think the problem has to do with updateCanvasCD being called by focusIn and focusOut.  Is this really necessary?  Should not changes sequences unless the design has actually changed.

**Comment by cjmyers** [comment]
Removing these calls fixes this problem.  Not sure though if it creates others when building designs.  Needs testing.

**Comment by michael13162** [comment]
It's funny you mention this, since I just found a bug with calling updateCanvasCD when the canvasCD is outside our namespace.  

I don't think that fix fixed this bug though.

**Comment by michael13162** [comment]
Actually, seeing as I can't seem to reproduce this anymore, I think it did fix this issue as well.  In this case, even though the canvasCD is in our namespace, since the imported part is no longer being updated all the time, the rootCD's sequence is also no longer being changed improperly to a bunch of N's.  

Closing for now.
