### ISSUE TITLE
Importing part from registry from top-level canvas editor does not create a sequence

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#117]
When you import a part from registry from top-level canvas editor (pencil), does not create a sequence for the part.

**Comment by michael13162** [comment]
Check what the differences are between importing part using pencil vs using normal edit part button.

**Comment by michael13162** [comment]
It seems like the sequence is being converted to my own namespace when imported via editCanvasCD, and isn't when imported via editSelectedCD.  This causes the link from CD to Seq to break.

**Comment by michael13162** [comment]
This unconvered a huge bug with updateCanvasCD and registry parts.  In short, registry parts/parts outside of our namespace should never be changed.  Only parts inside our namespace should be able to be changed.  This was causing all sorts of issues with dragging parts around and overwriting SAs and SCs.
