### ISSUE TITLE
Include the URI link in the part editor

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#123]

**Comment by michael13162** [comment]
Done.  I also reorganized the order the PartEditDialog display's fields.

**Comment by michael13162** [comment]
Reopen this issue if you want me to change the label that is displayed from "URI" to something else that is more understandable/intuitive.

**Comment by cjmyers** [comment]
We call it “Identity” in the library, but I’m not sure that is more understandable.  Open to suggestions.

**Comment by michael13162** [comment]
Colloquially/in the email threads, we refer to it as a part's URI, so I think it might be good to stick with URI for now to avoid confusion.  If we think of a better name in the future, we can change it.

**Comment by cjmyers** [comment]
sure
