### ISSUE TITLE
Change upload to use synbiohub rather than sbolStack frontend

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#124]
1) If already logged in, go to step 3
2) Get user login info and do a /login POST request to synbiohub
3) Get submission info (see synbiohub submit page) combine with user info and SBOL file, and do a submit POST request.
4) Check that submission worked, if not report an error.
5) URI will be returned, potentially can use to get the part back and have it linked to SynBioHub.

**Comment by michael13162** [comment]
Example of the interface, as used by synbiohub webpage:
https://github.com/ICO2S/synbiohub/blob/master/lib/views/submit.js

**Comment by michael13162** [comment]
Example of login post request, as used by the synbiohub webpage:
https://github.com/ICO2S/synbiohub/blob/master/lib/views/login.js

**Comment by michael13162** [comment]
I have pushed my changes, but have left a couple TODOs in UploadDialog.java.  I tried to figure out the structure of the POST request as much as I could from the synbiohub javascript, but without further documentation and with my limited javascript knowledge, I still have some missing links.

Also, will some of this API change if we move some of the work to be handled by the Stack?

**Comment by cjmyers** [comment]
Hopefully not, if I do it correctly.  I will tackle this tomorrow morning.

Also not sure why synbiohub.utah.edu:9090 not responding but the data base still working.  Maybe switching to port 80 caused a problem.  Will look into that too.

**Comment by cjmyers** [comment]
We have discussed this today, and we agree that it is good to move this to stack, but it will take a little bit to execute.

As for your interface, I think you should have login and submit information on separate windows.  The reason is that once logged in, you don’t need to ask that again.  You should be able to store the token that you receive.

As for serializing the document, this will do it:

    private String serializeDocument(SBOLDocument document) throws StackException
    {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        
        try
        {
            SBOLWriter.write(document,  outputStream);
            
            return outputStream.toString("UTF-8");
        }
        catch(Exception e)
        {
            throw new StackException("Error serializing SBOL document", e);
        }
        
    }

I’m thinking we should put this code into SBOLStack frontend somehow.  However, I guess we can port it in once it is working.  By the way, did you keep the old upload code?  You should be able to use your new windows with the old code to fill in the submission information.  In this way, upload will continue to work for now just without authentication.

**Comment by michael13162** [comment]
I've added basic functionality.  It works like a charm!  The StackFrontend enhancements + registry saving in SBOLDocuments are fantastic!

I'll continue working on it over the weekend and try to make the UI look better.

Since the login information is stored in the SBOLDocument, and since I generate a new SBOLDocument every time I try to upload (in order to clean up all the fragments/objects of the "design" SBOLDocument), I'll have to save login information elsewhere if I want to remember user synbiohub accounts.  I'm currently autocompleting the username/email since I have access to that.

Do you think I should store a hashed password in a preferences node?  That's pretty much the only way to remember accounts since the logged in SBOLDocument is transient.  If not, asking the user to provide a password doesn't seem like such a bad idea.

**Comment by cjmyers** [comment]
The login bit in SBOLStack Frontend is not good right now.  The user credentials are not verified on the server end right now.  Also, it is not particularly secure to send you everything back about the user.  Instead, we likely should pass back some sort of session token.  Perhaps login would return this rather than store within SBOLDocument.  You could then hang onto that and pass that back each time you want to submit.  Probably need to talk it through with James though before making a change.

**Comment by michael13162** [comment]
Ernst uses https://jwt.io/introduction/ in BOOST to store a user's authentication.  We could do something similar.

**Comment by cjmyers** [comment]
Looks useful.

**Comment by cjmyers** [comment]
Done
