### ISSUE TITLE
Change UI for submission to synbiohub

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#127]
Remove purpose and chassis.

Add radio button:
If existing:
Prevent submission
Overwrite
Merge

should encode as '0', '1', '2', respectively, and strings not integers.
Note that Merge should disallow name/description to be entered as will be used from first submission with same id/version.

**Comment by cjmyers** [comment]
Names and operations for overwrite/merge, changed:

'0': Prevent if submission exists 
'1': Overwrite entire submission
'2': Merge and prevent if existing objects
'3': Merge and replace if existing objects

This is not implemented yet, but basically the difference is merge needed to be split into two separate behaviors and general merged had to be removed.  

We should probably discuss primary use cases by designer.

**Comment by cjmyers** [comment]
I think SBOLDesigner would primarily use the two Merge options.  Namely, in SBOLDesigner, you are usually working on one part of a submission.  You either want to "Overwrite" or create a "New Version" as per save.  The "Merge and Prevent" is basically you do not want to overwrite, you want to ensure that what is saved is uniquely identified and does not replace anything else.  The "Merge and Replace" option says you want to overwrite the existing part in the submission, if one already exists.

This is more parallel with how you treat documents.  Namely, you really only consider the individual object that you are working on within the document.  Let me know if this does not make sense.  Note I have not implemented this style of merges yet.  Right now, you can only overwrite an entire submission or merge with existing (not replace).  Will let you know when it is added.

**Comment by michael13162** [comment]
I have added basic support for these various options with my latest commit.  This still needs to be tested/refined, but it should give basic functionality when it comes to these options.  I have also added many TODOs for improvements to the UploadDialog.  We can discuss details during our meeting on Thursday.

**Comment by cjmyers** [comment]
I tweaked the upload window a bit.

**Comment by michael13162** [comment]
Chris:

Merge should now work on submit.  Please change the names to:

Prevent Submission
Overwrite Submission
Merge and Prevent, if existing
Merge and Replace, if existing

Also, please make it a combo box like iBioSim.

Thanks,

Chris

**Comment by michael13162** [comment]
I've updated UploadDialog and tested the submission options a bit.  The info message about the different options could probably be changed a bit.

**Comment by michael13162** [comment]
Change ui to match: http://synbiohub.utah.edu/submit

Specifically, collections replace keywords and options names have changed.

**Comment by michael13162** [comment]
The options have been updated and collections has replaced keywords.  However, when trying to get all collections from the java api, it crashes.  My SearchCriteria might not be correct.

**Comment by cjmyers** [comment]
Can you provide more detail about the crash and how you setup your search criteria?

Chris

**Comment by michael13162** [comment]
http://wiki.synbiohub.org/wiki/HTTP_API specifies how to search for specific collections, but not all collections.  I put "key: collection, value:", which I'm pretty sure is why it's incorrect.

**Comment by cjmyers** [comment]
http://synbiohub.org/remoteSearch/objectType%3DCollection&?limit=10000

**Comment by michael13162** [comment]
I see.

`				SearchQuery query = new SearchQuery();
				SearchCriteria crit = new SearchCriteria();
				crit.setKey("objectType");
				crit.setValue("Collection");
				query.addCriteria(crit);
				List<IdentifiedMetadata> results = stack.search(query);`

This is how I am constructing the query, and it's throwing:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

Do you see what I'm doing wrong?

**Comment by cjmyers** [comment]
I think you might need to set the offset and limit.

**Comment by michael13162** [comment]
Yup, that fixed it.  I've pushed a working (maybe) collections browser.

**Comment by michael13162** [comment]
I've added a better-looking way to select collections, but the submit call now hangs.  I've checked that I'm forming the comma separated collections string correctly, and it appears that I am.

**Comment by michael13162** [comment]
I have updated libSBOLj and submit now works, but I can't tell if it's being put in the correct collections (given I choose extra collections).  Is there an easy way to tell from the SynBioHub submissions/part page?

**Comment by michael13162** [comment]
I think it works!  Collections show up properly after making the parts public in synbiohub/submissions.
