### ISSUE TITLE
Mark Fields/Properties when editing part information

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#128]
It would be a nice feature to mark which field/property are required when editing a part's information. Field property such as Name and Description is optional and I would like some form of indication to know which text box is required to fill out. This way, the message box that pops up when I click Save doesn't have to warn me that I am not having inconsistent information.

**Comment by michael13162** [comment]
Required fields in the upload dialog are now marked with (*).  Also, the upload button will always be grayed out unless all the required fields are filled in.
