### ISSUE TITLE
Extra white space in Role Refinement options

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#129]
There is an extra space in " constitutive promoter" in the Role Refinement field. This white space is consistent for all Role Refinement options.

<img width="689" alt="white_space" src="https://cloud.githubusercontent.com/assets/7537729/22321461/448998da-e352-11e6-8341-477af90cccbb.png">

**Comment by cjmyers** [comment]
This is a mac style issue and cannot be changed.
