### ISSUE TITLE
Misspelled word in dialog box

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#130]
Design is spelled incorrectly on message dialog box.

<img width="643" alt="syntax_err" src="https://cloud.githubusercontent.com/assets/7537729/22321592/557eab16-e353-11e6-9b5d-794bf66a09fc.png">

**Comment by michael13162** [comment]
Also, it's no longer the "SBOL Stack" instance, but should be "SynBioHub" instance.  Good find Tramy!

**Comment by tramyn** [comment]
@michael13162 I was going to create an issue about the title for "SynbioHub". Thanks Michael.
