### ISSUE TITLE
Do not let people quit if file is not saved

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#133]
If a file is created and not saved, user should not be able to quit until after they are asked if it is okay to lose their work.

**Comment by michael13162** [comment]
I thought it was already doing this?

**Comment by michael13162** [comment]
This is a mac thing.

**Comment by michael13162** [comment]
I've added AppleJavaExtensions-1.4 to the pom.xml, but it seems to be missing some necessary classes (noticeably the QuitHandler).  I'm not sure why this is a problem.  Is it the same on a mac if you go to "Maven Dependencies" -> "AppleJavaExtensions-1.4.jar" -> "com.apple.eawt" -> "QuitHandler"?
