### ISSUE TITLE
Only submit parts in your namespace to SynBioHub

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#134]
Should only submit parts you created and not parts you used from SynBioHub.

**Comment by michael13162** [comment]
Documenting:

Chris: you should now be able to NOT submit parts outside your namespace.  You can see how I did this in iBioSim’s submit.  Basically, I removed all TopLevels not in my namespace before submitting.  Note, you will need a new libSBOLj, since I added a removeTopLevel function.

**Comment by cjmyers** [comment]
Done
