### ISSUE TITLE
Should be able to fetch a private store design to continue editing on

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#139]
Should be able to pull in a design you've stored on your private repository to continue work on.

**Comment by cjmyers** [comment]
When you login, you should receive the store name for the private store.  You then should be able to use that to fetch the list of parts instead of the public store graph.  

Will need to change namespaces back once back in SBOLDesigner.

**Comment by michael13162** [comment]
This is done.
