### ISSUE TITLE
Use new SynBioHub GET search query

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#144]
Hi,

I’ve added a new GET search endpoint /remoteSearch described here:

http://wiki.synbiohub.org/index.php/HTTP_API

I would like this one to replace the POST search endpoint which is much less general.  The GET search enables search as almost any field.

Michael: I’ve added a new search method to the SynBioHub frontend code that takes a general search query object.  You might want to start using this method, since it will enable to you build any query you might need.  For now, the getMatchingComponentDefinitions method is still there with the same API to construct these queries for you.  Note I did need to change offset to 0 and limit to 10000, you were sending null and these are now required fields.  Otherwise, your code is unchanged.

Let me know if you all have any comments on this.

Cheers,

Chris

**Comment by michael13162** [comment]
I've replaced getMatchingComponentDefinitions with the more flexible SearchQuery.

**Comment by michael13162** [comment]
I would recommend updating the documentation to explicitly say that multiple key=value pairs for the same key evaluates as an "or" function.  Also, the example should be extended to show how the "search string" works.

**Comment by michael13162** [comment]
@cjmyers I'm not sure when this happened, but synbiohub.utah.edu no longer returns anything from the queries.  I don't think this is an SBOLDesigner bug because getMatchingCDs and SearchQuery are pretty much the same thing, and it does still work with synbiohub.org.  Have there been any changes recently?

**Comment by cjmyers** [comment]
Strange it is working for me.  Are you logged in?  There are no public parts on this one.

**Comment by michael13162** [comment]
Oops, I totally forgot about that.  Nevermind, everything's working great 👍
