### ISSUE TITLE
Browser opens with all parts even though DNA selected

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#146]

**Comment by michael13162** [comment]
Which browser is this?  I can't seem to reproduce in the RegistryInputDialog or RootCDSelectionDialog.

**Comment by cjmyers** [comment]
It is the one when you open a document.

**Comment by michael13162** [comment]
I believe I have fixed this in SBOLDesigner now.  I've also updated the jar in iBioSim.  However, I was never able to reproduce this in the first place, so it's probably good to check to make sure.  

Closing for now.

**Comment by cjmyers** [comment]
Appears to be fixed.
