### ISSUE TITLE
Lock out Part Role/Refinement when neither DNA/RNA are selected.

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#147]

**Comment by michael13162** [comment]
I have added this feature to RegistryInputDialog.

**Comment by cjmyers** [comment]
Looks good.  Has this been added to iBioSim?

**Comment by michael13162** [comment]
Just updated SBOLDesigner.jar in iBioSim, so it should work there now.

**Comment by cjmyers** [comment]
One minor thing I noticed is that in iBioSim, it initially opens to All Types, but they roles are not greyed out.  If you switch to Protein, they grey out and stay greyed out afterwards.

**Comment by michael13162** [comment]
Good catch.  I've fixed this in SBOLDesigner and updated the jar in iBioSim.

Just to confirm, they stay greyed out when you switch to Protein, but then go back to being not greyed out if you switch back to DNA/RNA right?

**Comment by cjmyers** [comment]
Yep
