### ISSUE TITLE
Unable to browse Collection in part registry 

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#149]
When browsing part registry, I am unable to filter Collection. The only option I am given is to browse from All Collections from the iGem SBOL Registry. 

![collection_browsing](https://cloud.githubusercontent.com/assets/7537729/24920000/d5074278-1ea2-11e7-8f26-5b58e9e665b9.png)

**Comment by cjmyers** [comment]
The way this works is like a file tree.  Namely, if you select igem_collection, you can then select to go back to All Collections.  If within, igem, you select categories, you then have the option to go back to igem_collection or all collections.  It is just like the directory selection you have in a file browser on a Mac.  So, it is not so much as filter by Collection but indicates which Collection you are looking at.  Does this make sense?

Chris

**Comment by michael13162** [comment]
I am closing the issue.
