### ISSUE TITLE
Unable to upload to new repositories

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#153]
If I try to add a registry, it is added to list, but I cannot upload to the new one.  It is not in that list.

**Comment by michael13162** [comment]
I haven't been able to reproduce this bug.  Also, I only show registries whose locations start with "http://".  What is the location of the registry you're trying to upload to?

**Comment by cjmyers** [comment]
Ah, that must be the problem.  It begins with: https://

Would be good to allow that as we may start moving to using secure transactions soon.  They are using https here.

**Comment by michael13162** [comment]
Done.  Upload now works with https:// locations.

**Comment by cjmyers** [comment]
It is allowed now, but does not seem to work.  There is some issue with certifications.  Need to figure out how https actually works.  Likely libSBOLj’s synbiohub frontend will need to handle this, I think.

Oops, just tried fetching parts, and it seems to strip out a back slash and get confused.  Re-opening.  Below is the registry address in question:

https://synbiohub.cidarlab.org

**Comment by michael13162** [comment]
I think it may be working now.  I've tried it with https://synbiohub.cidarlab.org, but there are no parts there.

**Comment by cjmyers** [comment]
You should have seen the ICE parts.  I do with with cidarlab.org:7777.  Might not be your problem though.  It could be with the synbiohub frontend.

**Comment by michael13162** [comment]
So this is confirmed working now?

If so, you can close the issue.

**Comment by cjmyers** [comment]
Works closing.
