### ISSUE TITLE
Remember last Collection selected

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#154]
It would be good to remember which Collection was last viewed (like you do for registries) and default to that one when you open the registry browser again.  This should speed things up considerably as the number of total parts grows.

Also, having a new "Root Collections" option in Collections could be useful:

All Collections (no filter on collections)
Root Collections (only show root collections)
<CollectionId> (filter on this collection)

This could avoid the fetch all parts which is slow as you could navigate to Root Collections rather than All Collections, and that list would be smaller.

**Comment by michael13162** [comment]
I believe what you're thinking of as All Collections and Root Collections are actually the same thing.  All Collections doesn't do a fetch all parts.  It fetches only the root collections.  I've renamed All Collections to Root Collections to make this more clear (since it does only fetch the root collections).

**Comment by michael13162** [comment]
I've just made this change.  This actually fits very well semantically with how SynBioHub is organized.  All parts in SynBioHub are contained directly or transitively in the root collections, so it makes sense to think of the collection hierarchy as some sort of file tree.  Now the semantics match the actual implementation.

I will work on persisting the most recent collection.  This involves saving the collection path in Registry preferences, which is hacky, but doable.

**Comment by cjmyers** [comment]
Sounds good.  This will greatly speed things up for users.

**Comment by michael13162** [comment]
I've been thinking about this more: A much cleaner implementation will be to statically cache the collection paths in RegistryInputDialog similar to how SynBioHubFrontends are currently being cached.  Is it ok that the paths don't persist after SBOLDesigner is closed?  Usually, you fetch things repeatedly per instance of SBOLDesigner, and not across sessions.

Anyway, pretty much the same result, but probably 1/2 the implementation complexity.  And cross-session persistence could always be added later outside of Registries.

**Comment by cjmyers** [comment]
Yes, it is usually within a single session, so this should solve most use cases.

**Comment by michael13162** [comment]
https://github.com/SynBioDex/SBOLDesigner/commit/11a0764bfcaecfa7ee31153c757bca4bd09951b4 implements this.  In this process, I also caught this bug which we've been noticing for a long time now: https://github.com/SynBioDex/SBOLDesigner/issues/195
