### ISSUE TITLE
Remove BOOST functionality and protobufs

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#159]
After this, we shouldn't need to do mvn generate-sources.

**Comment by eoberortner** [comment]
I do hope that this means that the BOOST functionality should be removed just for milestone 2.2. :)
Thanks for clarifying!

**Comment by michael13162** [comment]
Yes, this is definitely just temporary.  We're trying to do a release soon, and we're just cleaning partial features and tabling them for after the release.

**Comment by eoberortner** [comment]
Thanks you! 
Please don't hesitate to contact me as soon as you're ready for integrating BOOST.

**Comment by michael13162** [comment]
I'm currently at Google (Mountain View) doing an internship, so I'm only 1 hour drive away from JGI.  If you want to get together at some point this summer and hack on things a bit, let me know :)

**Comment by michael13162** [comment]
This is now temporarily removed.

**Comment by cjmyers** [comment]
Good, but export likely needs a cancel button.

**Comment by michael13162** [comment]
There is now a cancel button.
