### ISSUE TITLE
Remove SBOLDesigner agent from PartEditDialog and refer to a page on SynBioHub instead

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#160]

**Comment by michael13162** [comment]
The URI should be something like:
http://synbiohub.org/public/Software/SBOLDesigner/2.2

**Comment by michael13162** [comment]
Also, SynBioHub will need to be updated so this URI is dereferenceable.

**Comment by cjmyers** [comment]
Moved comments to #119
