### ISSUE TITLE
Change default to synbiohub.org to https

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#162]
Once synbiohub.org moves to https, then so should SBOLDesigners default registries.

**Comment by cjmyers** [comment]
synbiohub.org has moved, so please change default to https://synbiohub.org

Both the URI prefix and URL

This also means new URIs for the built in file.  You can get that file from here:

https://www.dropbox.com/s/nf6wfjkrlwv68n1/iGEM_2017_collection.xml?dl=0

Finally, this means a new URI for the SBOLDesigner agent which should be:

https://synbiohub.org/public/SBOL_Software/SBOLDesigner/2.2

**Comment by cjmyers** [comment]
Updated defaults but should migrate any current users.

**Comment by michael13162** [comment]
There is now a wrapper around SynBioHubFrontend creation so users still on http://synbiohub.org get rerouted to https://synbiohub.org.

**Comment by cjmyers** [comment]
Does it update the preference?

**Comment by michael13162** [comment]
No, but this rerouting will happen every time so the end result should be the same.  Do you want me to also update the preference?

**Comment by cjmyers** [comment]
Would be nice, since we are now using these in other places in iBioSim.

**Comment by michael13162** [comment]
I have implemented this, but I am not sure if it works.  The bug with synbiohub earlier is interfering with testing it seems.
