### ISSUE TITLE
Only show root collections initially for a new part registry

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#164]
When you move to a new registry, only show the root collections.  This will make initial loads of registries much faster.  I've implemented this.

However, this will be come tedious if not coupled with remembering the last collection.  

See issue #163 .

Michael: please double check my change.

**Comment by michael13162** [comment]
I may have thought of a potential edge case.  Parts will now only be fetched if collections isn't empty to begin with.  If a registry doesn't have any collections, then parts will never be fetched.  Will every registry definitely have a collection, and will all parts always belong in a collection?

**Comment by cjmyers** [comment]
Good point.  All SynBioHub’s do have a parts organized in Collections, but this might not be a safe assumption.  If the list of Collections fetched is empty, should go ahead and fetch all parts.

**Comment by michael13162** [comment]
Sounds good 👍

**Comment by michael13162** [comment]
Actually, there may still be a problem.  Imagine a registry with a collection with parts inside, but also parts that aren't contained in a collection.  The parts that aren't in a collection will never be fetched since the list of root collections will never be empty.  Do I have this right?

**Comment by cjmyers** [comment]
Yes, this is theoretically possible, but not in SynBioHub.  Maybe we can leave this note open for next version.

The problem with getting all parts is that it makes changing registries very slow and you continue the fetch even if you change immediately due to the threading.  So, I think optimizing for SynBioHub is fine now, since that is the only type of registries we support currently.

**Comment by michael13162** [comment]
I am moving this to 2.3 so we know this is still an issue.  For now, I have changed the logic so if root collections do exist, only they are shown.  However, if they don't exist, then parts are fetched.

Note for future reference: There is a bug when a registry contains parts that aren't contained in a collection where they will never get fetched.

**Comment by michael13162** [comment]
I am closing this issue since SynBioHub requires all parts to exist within one or more collections.  If this ever changes, then those parts will not be visible to SBOLDesigner.
