### ISSUE TITLE
Reference SynBioHub should be HTTPS, not HTTP

### ISSUE THREAD

**Issue by NeilWipat** [SynBioDex/SBOLDesigner#165]

**Comment by cjmyers** [comment]
We did switch this yesterday.  Where are you seeing it as http?

**Comment by NeilWipat** [comment]
Wherever the download link takes us for SBOL Designer – Github?

**Comment by cjmyers** [comment]
Oh, sorry yes this has not yet been changed on SBOLDesigner.  There is another issue #162 which addresses this.

**Comment by cjmyers** [comment]
For now, you need to change this in the "registries" preferences to https://synbiohub.org.  Make sure to change both URI Prefix and URL.

**Comment by cjmyers** [comment]
Updated defaults to https
