### ISSUE TITLE
Change prov:creator to dc:creator

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#166]
This should be changed both in the activity and the agent on SynBioHub.

**Comment by michael13162** [comment]
I have changed prov:creator to dcterms:creator, which is what I found in other sbol files.  Is this correct?

**Comment by cjmyers** [comment]
I  think dc creator. Grab an igem file to check

Chris

**Comment by michael13162** [comment]
You're right, it's dc:creator.  It should be correct now.  Thanks!

**Comment by cjmyers** [comment]
Please send me the new SBOL Agent for SBOLDesigner with corrected dc terms, so I can post on synbiohub.org

**Comment by michael13162** [comment]
Sorry it's in a zip, GitHub doesn't allow XML attachments for some reason.

[SBOLDesignerAgent.zip](https://github.com/SynBioDex/SBOLDesigner/files/1126882/SBOLDesignerAgent.zip)

**Comment by michael13162** [comment]
Do you want me to update the release jar now that these fixes are in?

**Comment by cjmyers** [comment]
Updated now, even with the reference:

https://dev.synbiohub.org/public/SBOL_Software/SBOLDesigner/2.2 <https://dev.synbiohub.org/public/SBOL_Software/SBOLDesigner/2.2>

**Comment by cjmyers** [comment]
It is not quite right yet.  We are missing the “hadRole” field on Association.  I’m emailing others for feedback.

We might also want to add a bit more to the Activity such as a Name and Description to make the pages look a little nicer.

Maybe something like:

Name: SBOLDesigner 2.2 Activity
Description: This design was created by SBOLDesigner 2.2.

or something similar.
