### ISSUE TITLE
Allow browsing of SynBioHub private parts

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#168]
-Registry needs to store the authenticated token
-Preferences needs a way to log in
-SynBioHub Java API needs to allow browsing of private parts (rootCollections, subCollections, search, get, submit)

**Comment by michael13162** [comment]
This is now implemented.  SynBioHubFrontends stores logged in SynBioHubFrontend instances, and you can log in using the "login" button in Registry preferences.  Everything seems to be working as intended on my side, but I haven't been able to see any private constructs while searching.  Upload and login have been working great though!  @cjmyers, has synbiohub.utah.edu been updated with the new functionality?

Please give it a try :)

Remaining TODOs: RegistryPreferencesDialog should only show the login button when the Registry is a SynBioHub instance and not a file.

**Comment by cjmyers** [comment]
Have you submitted any? Should be able to submit and see immediately.

Chris

**Comment by michael13162** [comment]
I logged in, submitted some parts, and they show up on the website.  However, when I search for them in SBOLDesigner (still while logged in), I can't find them.  I see the collection the submission made (which I assume is private?), but there are no parts.

**Comment by cjmyers** [comment]
Strange.  It is actually working for me.  If you are around the office today, perhaps we can take a look.

**Comment by michael13162** [comment]
Well, that's good to hear.  I'll probably drop by around noon today.

**Comment by michael13162** [comment]
Finished remaining TODO about preventing users from logging into file Registries.  Everything has been tested and confirmed working.
