### ISSUE TITLE
SBOL Designer Doesn't Recognize Attachments 

### ISSUE THREAD

**Issue by dwootton** [SynBioDex/SBOLDesigner#171]
After verifying that I am correctly logged in to the Utah SynbioHub Registry and going to the proper collection for my toggle switch, I am still unable to view any of my submitted parts for the toggle switch.  I think the issue is that all of my parts were submitted to the collection as attachments, and while I can see components in SBOL designer, all of my genebank files were categorized as attachments and are not present on SBOL designer. They are still not present when I select All part for Part Role and None for Role refinement.

**Comment by cjmyers** [comment]
Oops.  You should never submit parts as attachments.  This is not the correct way.  You need to submit the parts using the Submit page.  

Attachments are only for images, data, etc.  

BTW: did you submit GenBank or FASTA for your parts?  If GenBank, you should resubmit the parts.  If FASTA, you can build your parts using SBOLDesigner and attach a sequence to each part as you build them in SBOLDesigner.  This will allow you to indicate their Role, etc.

**Comment by dwootton** [comment]
When I go through the formal submission process (hitting the submit button, going to submit existing collection, selecting the private collection, and submitting the file) the file will still upload as an attachment. This is still the case when I select 'overwrite existing object'. 

When I delete the attachment from the collection and try to re add it using submit, the component never appears in my collection. It doesn't appear as an attachment or component- it just never appears.

I submitted GenBank standard files (.gb). I'm generating these files using snapgene (a plasmid editor that recognizes features on submitted DNA sequences). Could this be part of the error?

**Comment by cjmyers** [comment]
This is very odd. Could you send me an example file to myers@ece.utah.edu?

Chris

**Comment by michael13162** [comment]
Is this still a bug related to SBOLDesigner?  If not, feel free to close.
