### ISSUE TITLE
Remove Collection selection from Submit page

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#174]
This part is confusing, so lets go ahead and remove it.  Will also allow submit to open faster since can be long list sometimes.

**Comment by michael13162** [comment]
I have removed it.  Should the "options" drop-down menu still be there?  Should submit to existing collections have the drop down menu?

**Comment by cjmyers** [comment]
Yes but option depend on whether submitting to old or new collection. See submit page on sbh.

Chris

**Comment by cjmyers** [comment]
You don’t need the dropdown, but you need an option to select “Overwrite Existing Objects”.  If not selected, then the overwrite_merge parameter to submit should be “0”, and if it is selected, it should be “1”.

**Comment by michael13162** [comment]
Done.
