### ISSUE TITLE
Add ability to submit into an existing collection

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#175]
Should be able to submit to new or existing collection.  See how it is done on synbiohub with tabs, as may be good way to do in SBOLDesigner too.

To get the collections, do get root collections, then remove any that do have "/public/" in the URI after the namespace for the SBH instance.

**Comment by michael13162** [comment]
This is mostly done.  What's the exact way for me to call submit now?  I'm currently doing:
frontend.submit(null, null, null, null, null, getSelectedCollections(collections), null, toBeUploaded);

Also, should the options drop down menu be included here?

**Comment by cjmyers** [comment]
Good question. If you send same id then should go into same collection.

Need the merge options here and the prevent overwrite option for new collection.

Chris

**Comment by cjmyers** [comment]
This crashes since the text cannot be null.  Since you know the metadata for the selected Collection, please use that information:

submit(id, version, name, description, “”, “”, overwrite_merge, toBeUploaded)

There should be an option given to “Overwrite Existing Objects”.  If this is not selected, then overwrite_merge should be “2”, and it should be “3” if selected.

**Comment by michael13162** [comment]
Done.
