### ISSUE TITLE
Use Web of Registries to populate registries list

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#176]
SBOLDesigner should fetch the list of SynBioHub registries from the Web of Registries.

**Comment by michael13162** [comment]
Is there a library/Java API for this?

**Comment by cjmyers** [comment]
I don't think we have a library, but there should be documentation.  I cannot seem to find it though.  @zachzundel should point you to it.  It should also get linked on the README for the github repo for it.

**Comment by michael13162** [comment]
@zachzundel Could you point me to the docs?

**Comment by michael13162** [comment]
For future reference, Web of Registries docs are here: https://synbiohub.github.io/Web-of-Registries/?python#introduction

**Comment by michael13162** [comment]
e03d0926c4cdb089b4985db36d8e2f83edb57064

Now, whenever a user opens SBOLDesigner, registries from the Web of Registries that aren't in the user's registry list are added.  This also happens when the user clicks on "restore defaults" in registry preferences.
