### ISSUE TITLE
Ensure certificate for letsencrypt exists

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#178]
Add code to SBOLDesigner to check for the letsencrypt certificate on startup and add it if missing.

**Comment by michael13162** [comment]
This person's answer was very helpful: https://stackoverflow.com/questions/24043397/options-for-programatically-adding-certificates-to-java-keystore

**Comment by michael13162** [comment]
Done.  Note that this is a form of "hardcoding" since we're adding a certificate file that's in the actual jar.  This instance expires in 2020, so the certificate will need to be re-acquired and updated before then.
