### ISSUE TITLE
Import FASTA support

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#18]
Add a button near sequence editor to allow user to import FASTA file for the sequence.

**Comment by cjmyers** [comment]
If FASTA file has a single sequence, this should be attached to the CD being edited.

If FASTA file has multiple sequences, either throw error, OR pop up window and list the descriptions.

**Comment by michael13162** [comment]
Done.  If FASTA file has no sequences, reports to the user.  If one sequence, imports it.  If multiple sequences, asks the user to choose which one to use.

**Comment by michael13162** [comment]
Done. If FASTA file has no sequences, reports to the user. If one sequence, imports it. If multiple sequences, asks the user to choose which one to use.

**Comment by michael13162** [comment]
Reader has bug if Fasta file is empty.  Redo implementation when that is fixed.  Also, could change to "import seqeunce" and use any file's (sbol, gb) sequences.  Could do the same with other file's CDs.

Alternatively, replace with an "import data" button that looks at all CDs with the correct role and type.  Same with Sequences.
