### ISSUE TITLE
Update the SBOLDesigner video

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#180]
The UI has changed and it's out of date.

**Comment by sboldesigner** [comment]
New tutorial videos have been uploaded to the new SBOLDesigner documentation page at sboldesigner.github.io

**Comment by massivefish** [comment]
New tutorial videos have been added to the documentation page at sboldesigner.github.io

**Comment by michael13162** [comment]
Looks good!  @cjmyers What do you think?

**Comment by cjmyers** [comment]
This page and the tutorials look good.  The last one on combinatorial design will not go fullscreen for some reason though the others do.

Please make sure all content is copied onto this page from here:

http://www.async.ece.utah.edu/SBOLDesigner

The publication and credits are one thing I can see that is missing.

Once this is done, it can be the page linked from our webpage for SBOLDesigner.

Thanks.

**Comment by yu-eric** [comment]
I have updated the website with all of the information from the Myers web page, and fixed all of the videos.

**Comment by cjmyers** [comment]
Done
