### ISSUE TITLE
Show composite using dashes coming out of glyph

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#181]
When a CD has Components, then render the glyph with a dash coming out of each corner.  This will enable a user to see whether or not there is sub-structure.

**Comment by jakebeal** [comment]
I would suggest you might want to use the "omitted backbone" form instead.  It makes a sort of nice "drawer"

 ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/86de2f5/Glyphs/composite/abbreviated-composite-example2.png)

**Comment by michael13162** [comment]
This has been replaced by https://github.com/SynBioDex/SBOLDesigner/issues/187

Note: the current plan is to adopt what Jake has proposed above.
