### ISSUE TITLE
SEP V003 - Distinguished Unknowns

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#187]
https://github.com/SynBioDex/SBOLv-realizations/issues/6

**Comment by cjmyers** [comment]
Does the composite lines need to touch the backbone?

**Comment by jakebeal** [comment]
The composite lines need to touch the bounding box of the base glyph.  In many cases, that will be at the backbone.

**Comment by cjmyers** [comment]
Not doing.  Closing.
