### ISSUE TITLE
Open RootURI sent via SBOLDesigner plugin

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#193]
createRecursiveCopy is not guaranteed return a document with a single root CD if there is a reference to a CD that is not through a definition.  

This happens in openDocument in SBOLDesignerPlugin.  Namely, it uses the rootURI to extract the design from the document.  Then, getDesign().load is called, it may have more than one root, but it has already been specified which rootURI to use, so it should respect that choice and not open a dialog.

**Comment by michael13162** [comment]
This is done and I think you've confirmed its fixed.
