### ISSUE TITLE
Invalid Activity generated as missing hadRole field

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#196]
The hadRole is a required field and it is missing in the Activity generated.  Currently, we do not have a good ontology for roles on associations, so you will need to make one up for now.  

http://sbols.org/v2#sequenceEditor

Also, PROV-O is now supported in libSBOLj, so please revise your code to use the native methods to avoid these kind of problems.

**Comment by bbartley** [comment]
SEP 19 recommends using sbol:design, sbol:build, sbol:test, or sbol:learn on Associations (as well as Usages)
Bryan

**Comment by cjmyers** [comment]
I guess that could work to use sbol:design.  Not very precise but it could serve for now.

**Comment by michael13162** [comment]
I am using:

http://sbols.org/v2#sequenceEditor

Is this ok for now?

**Comment by cjmyers** [comment]
Is this for Association?

I think it is okay though not a true ontology term as of yet.  Might be a good thing to discuss with sbol-dev at some point.

Chris

**Comment by michael13162** [comment]
Correct, this is for Association.

I'll close the issue for now, but we can change the exact term after it gets discussed more.
