### ISSUE TITLE
Need a means to deal with large return results

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#197]
If your exceeded the number that can be returned in one shot, then when change your text entry in the search box, re-run search on synbiohub.

**Comment by michael13162** [comment]
0c93c9a573aa747df71ec44e98860fa7783ade72

Line 110 of SynBioHubQuery asks: @zachzundel How should I form the SearchCriteria for filterText?

The wiki (http://wiki.synbiohub.org/index.php/HTTP_API) is currently down, and I don't think it says explicitly either.

**Comment by cjmyers** [comment]
You can look in libSBOLj synbiohubfrontend code to see how.

**Comment by michael13162** [comment]
Yup, that answers my questions.  The key should be "name" according to libSBOLj.  This is also confirmed working.  Now, when a search doesn't return all possible results, typing in the filter text entry causes more searching to take place.

**Comment by cjmyers** [comment]
When filtering parts, if the query result exceeds the maximum search result (found in a preference), then you must keep querying as the user types.  Once it is below this maximum, the results are held as a cache and subsequent typing can filter within the cache.  The cache is invalidated when the filter string is no longer a proper superstring of the filter string used in the query that created the cache.

**Comment by cjmyers** [comment]
The cache of query results should be only created when a query returns less than the maximum search result limit.  The cache should be invalidated whenever a subsequent query that is consistent with the current filters returns and has a filter part string that is a proper subset of the current filter part string, and the result returns less than the search limit.

**Comment by cjmyers** [comment]
Replace the cache when the following are true:
1) Query result matches current user search request (filter part string can be a substring of the request).
2) Results returned are less than the maximum search result limit.
3) The filter part string for this request is a proper substring of the current cache.  In other words, the results returned are a superset of those stored in the cache.

**Comment by michael13162** [comment]
71b48c8c1b3396afe2df6274bd9826cdb620c0b5 makes these changes.  The logic ended up being difficult to get correct, and a long time was spent debugging and testing.  However, everything should be good now.
