### ISSUE TITLE
Browsing Part Window

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#200]
When clicking "Import registry part", the window for browsing parts is shown in the back of the Part window. Ideally, the browsing of part window should be on the foreground.

**Comment by michael13162** [comment]
Whenever I've tried this, the browsing parts window has been in the foreground.  Can you try to reproduce this?  If it's not possible, please close this issue.

**Comment by michael13162** [comment]
Punting to 2.4 because it's not reproducible for me and doesn't seem to be a problem with all Macs.

**Comment by cjmyers** [comment]
I've seen this.  It is likely not a problem when running in eclipse but perhaps when running standalone.

**Comment by cjmyers** [comment]
Should be fixed now, as frame was not sent to SBOLDesigner code.  Move this to iBioSim tracker, mark as needs testing by @tramyn.

**Comment by michael13162** [comment]
Moved to https://github.com/MyersResearchGroup/iBioSim/issues/477
