### ISSUE TITLE
Long message window

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/SBOLDesigner#203]
The contents for the message window should wrap the message so it doesn't get cut off on my display screen. Right now, the window for the message dialog is stretching my entire laptop screen.

<img width="1280" alt="screen shot 2017-11-06 at 10 53 27 am" src="https://user-images.githubusercontent.com/7537729/32455957-2971ffdc-c2e1-11e7-88be-b546e3ee5906.png">

**Comment by cjmyers** [comment]
Error messages should have an 80 character limit per line.  To fix, find the last space before the 80 character limit and split and wrap, repeat if necessary.

**Comment by michael13162** [comment]
I actually built a custom MessageDialog that takes care of all of this.  I've switched this usage of the normal JOptionPane dialog to MessageDialog.
