### ISSUE TITLE
Need a way to logout of a registry

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#205]
If you login to the wrong account, you might want to be able to logout to login again.  Also might be good to display which login is in use too, so you know.

**Comment by michael13162** [comment]
In SynBioHubFrontend, could there be a method like "getUsername()"?  It would return the user's username, or null if no one is logged in.  This would help with displaying which login is in use.

I've added a logout button to RegistryPreferencesTab, and all buttons are now fully context sensitive.

**Comment by cjmyers** [comment]
Yes, please log an issue on libsbolj tracker.

**Comment by michael13162** [comment]
Added https://github.com/SynBioDex/libSBOLj/issues/516

**Comment by michael13162** [comment]
RegistryPreferencesTab buttons are all fully context sensitive and user now knows which account is logged in.
