### ISSUE TITLE
Restrictions on operators zeroOrMore and oneOrMore

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#212]
See rule sbol-12903:

If the strategy property of a CombinatorialDerivation contains the URI http://sbols.org/v2#enumerate, then its variableComponents property MUST NOT contain a VariableComponent with an operator property that contains the URI http://sbols.org/v2#zeroOrMore or the URI http://sbols.org/v2#oneOrMore. Reference: Section 7.11 on page 47

So, this answers the question about meaning of zeroOrMore, oneOrMore.  This means when a ComboDerv has enumerate, you must remove the options zeroOrMore, oneOrMore from the operators.  This also means if a user has select one of these operators, they should not be able to change strategy to enumerate.

**Comment by michael13162** [comment]
It would be useful to have this as a validation rule in libSBOLj.  I would then be able to catch the exception and report (in a more friendly manner) that their action isn't allowed.  For example, this is how some actions are prevented in the PartEditDialog.

I could do the checks in SBOLDesigner, but it would duplicate what has to be in libSBOLj anyway.

**Comment by michael13162** [comment]
This is now implemented in the variant editor.
