### ISSUE TITLE
Save-As

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#217]
One cannot Save-As in SBOLDesigner-2.2 on a Mac, only Save.

**Comment by cjmyers** [comment]
Export might be what you are looking for.  When you select Export, you save the current working design into a new document in SBOL2 or other formats.  Does this work for you?  Would it be more understandable to change this to Save As?

**Comment by jakebeal** [comment]
The typical meaning of "export" is "to a file format without all features"
Following typical current UI practice, you could either rename to "save as" or have separate "save as" and "export" buttons.  "Export" is an optional notion in user interfaces, which is being slowly obsoleted by more sophisticated save dialogs; "Save As" is fundamental functionality.

**Comment by cjmyers** [comment]
Sounds good.  How about Save As being equivalent to Export -> SBOL2, while Export is used only for SBOL1, GenBank, and Fasta?

Also, just so you are aware, the Save As / Export features save your working design rather than your entire working document.

**Comment by jakebeal** [comment]
The Save-As/Export split you propose is fine.

If you're going to have the single design vs. "project" model, you really need to have a project view like Eclipse does too.

**Comment by cjmyers** [comment]
Agree this would be useful.  We actually use SBOLDesigner within iBioSim often which give the project view that you mention, though admittedly right now the SBOL is shown as a single file.  We should be able to expand this to see all the files inside.  We might also want to construct a similar "project view" to wrap the SBOLDesigner stand alone.

**Comment by michael13162** [comment]
Save as has been exported out of export and is now a separate button (floppy disk with a pencil to the right of the actual save button).

**Comment by cjmyers** [comment]
Looks good to me.

**Comment by jakebeal** [comment]
Looks OK, except for the larger issue of file vs. design, which is beyond the scope of this issue.
