### ISSUE TITLE
Warn if import is missing sequence

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#218]
When I imported BBa_E0040 (the most common GFP part), it turned out to have no sequence. I discovered this only by accident, wondering how the overall part sequence was so short.

SBOL designer should provide some sort of visual warning that there are parts with missing sequence information, e.g., by putting a little colorful modifier on their icon.

**Comment by cjmyers** [comment]
![screen shot 2018-01-16 at 2 29 07 pm](https://user-images.githubusercontent.com/3507191/35013159-acec5c2a-fac9-11e7-8677-fb49dcdc6d95.png)

**Comment by cjmyers** [comment]
Did you import from a file or registry?  When I import from SynBioHub.org it has a sequence.

Agree that an overlay to indicate a missing sequence would be good feature to have.  Any suggestions on an icon that would be good to overlay to indicate no sequence?

**Comment by jakebeal** [comment]
Since I could not access anything in SynBioHub.org, I imported from the "Built-in parts" registry.

**Comment by cjmyers** [comment]
Ah, that makes sense.  We don’t usually use that, and I can see now that BBa_E0040 has a problem in built-in parts.  We need to double-check this file.  It was generated from the online iGEM dataset as a sort of cache of the 2017 distribution, but it appears to have issues.

**Comment by jakebeal** [comment]
Even if you fix this instance, my base suggestion also remains: there should be a warning of blank sequences.

**Comment by cjmyers** [comment]
Agreed.  Any suggestions of a good icon overlay for this?

**Comment by jakebeal** [comment]
How about a little warning Emoji? 
https://emojipedia.org/warning-sign/

**Comment by cjmyers** [comment]
I like it.

**Comment by michael13162** [comment]
I've added the suggested warning emoji as an overlay that shows up whenever a part has missing sequences.  Each part image now also gets refreshed whenever the part is updated.
