### ISSUE TITLE
Part sequence entry should filter out whitespace

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#219]
When I paste a sequence in for a part that is missing a sequence, it typically has whitespace in it from the source (e.g., a FASTA file). SBOLDesigner-2.2 then refuses to accept this sequence because it has illegal characters.  I have to edit out the whitespace by hand, which is likely to cause errors and is certainly problematic for larger sequences.

Whitespace should simply be automatically ignored.

**Comment by cjmyers** [comment]
Good point.  We will trim all leading and trailing white space.

**Comment by michael13162** [comment]
Done.  Whitespace is now not allowed in the PartEditDialog sequence text area.

**Comment by jakebeal** [comment]
@michael13162 Not allowed? That's the opposite of the fix that is needed.  The point is that if I manually grab a sequence to paste in from somewhere, it will often be in a format like FASTA that has whitespace in the middle, e.g.,:

````
cacgaggcagacctcagcgctagcggagtgtatactggcttactatgttggcactgatgagggtgtcagt
gaagtgcttcatgtggcaggagaaaaaaggctgcaccggtgcgtcagcagaatatgtgatacaggatata
ttccgcttcctcgctcactgactcgctacgctcggtcgttcgactgcggcgagcggaaatggcttacgaa
cggggcggagatttcctggaagatgccaggaagatacttaacagggaagtgagagggccgcggcaaagcc
gtttttccataggctccgcccccctgacaagcatcacgaaatctgacgctcaaatcagtggtggcgaaac
ccgacaggactataaagataccaggcgtttcccctggcggctccctcgtgcgctctcctgttcctgcctt
tcggtttaccggtgtcattccgctgttatggccgcgtttgtctcattccacgcctgacactcagttccgg
gtaggcagttcgctccaagctggactgtatgcacgaaccccccgttcagtccgaccgctgcgccttatcc
ggtaactatcgtcttgagtccaacccggaaagacatgcaaaagcaccactggcagcagccactggtaatt
gatttagaggagttagtcttgaagtcatgcgccggttaaggctaaactgaaaggacaagttttggtgact
````

Whitespace should be allowed and get trimmed not just from start and end but the middle as well.

**Comment by michael13162** [comment]
That is what I meant.  Any text that is typed/pasted into the sequence field will be run through a regular expression that replaces all whitespace with empty strings.  This means it'll get removed from the start, end, and middle.
