### ISSUE TITLE
Error messages can't be copied

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#220]
I cannot copy and paste error messages into bug reports with SBOLDesigner-2.2 on my Mac.
This is a problem when there is a super-big error message and it might be useful for you to know what it was, because I'm not going to transcribe it.

**Comment by cjmyers** [comment]
This should be fixed on 3.0, but we will double check that all have been broken into multiple lines.

**Comment by michael13162** [comment]
I've replaced all the rest of the places where errors were being reported poorly in the GUI to the better multi-line/copy/pasteable dialog.
