### ISSUE TITLE
Cannot save design after editing part

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#221]
I edited BBa_E0040 to add in the missing sequence. Everything looked OK, but when I went to save, SBOLDesigner refused, saying:

    There was a problem saving this design: expected one element but was ...

Where the ... is something very long and complicated that I'm not going to try to transcribe by hand.

**Comment by cjmyers** [comment]
We think this one relates to a bug fix that went in after 2.2 release.  We will fix the error message dialog but would be good to know if this happens again using the latest version.

**Comment by jakebeal** [comment]
Have you got a binary you want me to test with?

**Comment by michael13162** [comment]
I just created one here: https://github.com/SynBioDex/SBOLDesigner/releases

Please download the one labeled 3.0 pre-release.  Thanks!

**Comment by jakebeal** [comment]
I ran into a problem reproducing the bug, per #235.  I thus don't know if this bug is reproducible or not.

**Comment by jakebeal** [comment]
Fixed for me, following test of new binary post resolution of #235
