### ISSUE TITLE
Rules on updating wasDerivedFrom

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#230]
Do not set wasDerivedFrom when the displayId is changed.

Only set wasDerivedFrom when New Version is select on save.

**Comment by cjmyers** [comment]
I tried this out and it almost works.  I created a design.  Saved it to a document.  Then modified the design.  Saved it as a new version.  However, it does not immediately update the open file as that new version.  This is a problem because when I submit now, it submit it as version 1.

The new version only takes effect if you reload the design.  So, what should happen is when you select save as new version, it should immediately close and re-open the new version you just created.  Otherwise, if you carry on editing or submit to synbiohub you are really working on Version 1 which is confusing.

**Comment by michael13162** [comment]
I've changed it to reload the design after creating a new version while saving.  I've tried it out, and seems fine, but probably needs more testing before release.

**Comment by cjmyers** [comment]
Seems close.  Somehow though I created a new version without saving.  I think maybe what happened is I tried to save as new version, then it said I had unnamed part, so I canceled, then renamed and saved again.  I did not notice, but it may have already up’ed my version at that point.

**Comment by michael13162** [comment]
I don't think I understand fully.  Specifically, asking to rename always happens before saving new versions (so it would have returned before getting to the new version code?).

**Comment by cjmyers** [comment]
Strange.  I see your point.  I cannot reproduce this.
