### ISSUE TITLE
After adding variants cannot save

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#233]
I have to press cancel which is not intuitive

**Comment by michael13162** [comment]
I understand what you mean.  In the data model, the part doesn't own or even link to the variants.  Instead, something else points to the part and collects all the variants.  Changing this behavior would be possible, but roundabout (creating the derivation/variable component/variants, but deleting it if cancel is pressed).  If one already exists, it'd have to be saved, a new version created, and the original restored if cancel is pressed.

To align more with the data model, it makes more sense to not have that button in the PartEditDialog, and instead have it as a separate button (maybe on the top bar, idk).

**Comment by cjmyers** [comment]
I like that suggestion.  So, it would be like registry search / edit part / etc.?  This would be better and more consistent.

What icon though?  I think you might consider the grid as the add variant and a new one for enumerate, but I’m not sure.

**Comment by cjmyers** [comment]
Would also be good to move the annotation editor to a button.

**Comment by michael13162** [comment]
If we move the annotation editor, then there would be no way to edit the annotations of the canvas cd (it can't be selected).  Moving the combinatorial button is a good idea though.

**Comment by cjmyers** [comment]
Good point.  We should see though if we can fix the bring to front issue.

**Comment by michael13162** [comment]
I tried your trick, but it causes that specific button to be highlighted in the PartEditDialog, which is not what we want (cancel should be highlighted).

**Comment by cjmyers** [comment]
I see.  Actually Login is highlighted in the registry as a result of my previous fix.  Maybe we could always focus on cancel button.

**Comment by michael13162** [comment]
The variants button has been extracted to the toolbar on top.  They are to the left of the expand combinatorial design icon (hovering should help and display the tool tip).

**Comment by cjmyers** [comment]
Looks good.  Though can you add a cancel button?  Or is this problematic due to need to keep original derivations?

**Comment by cjmyers** [comment]
Also, still need to figure out a better solution about the displayIds for the initial derivation.

**Comment by michael13162** [comment]
I've changed it so that it asks you for a displayId when creating the initial derivation.

**Comment by cjmyers** [comment]
That is better.  However, when I select to create a new derivation, it does not open up the variant editor for that new derivation it just closes the window.

I still think having a combo box for your derivations on the window would be nicer.  You should be able to have an action listener on the combo box and refresh the variant editor when this combo box is changed, much like you do when you change the registry or other options in the registry input dialog.

**Comment by SamuelSauce** [comment]
Fixed.
