### ISSUE TITLE
Lose all combinatorial derivations when you change the displayId

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#234]
I created a design and added variants.  I then tried to save and it said you should change name from unnamed part to a new id.  When I did that I lost the combinatorial derivations.

Likely need to migrate the combinatorial derivation templates when changing the displayId

**Comment by michael13162** [comment]
PartEditDialog now uses rename instead of createCopy so all references are updated.  I've tested it and it appears to be working properly.

**Comment by cjmyers** [comment]
This is working for me.
