### ISSUE TITLE
Error while deleting sequences on downloaded SBOL file from SynbioHub

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLDesigner#241]
I've downloaded a SBOL file from my instance in UtahSinbiohub. Copied it to my namespace. Then I removed parts of the circuit, and saved it. It asked me if I wanted to overwrite it, and I clicked overwrite. Afterwards, looking at the sequence of the circuits, it had a bunch of NNNNs at the end of the sequence. So it was atcgcatgactgatcgNNNNNNNN . Also, an error message kept jumping saying there was a problem with the sequence constraints.

**Comment by cjmyers** [comment]
Please try to reproduce for @michael13162

**Comment by michael13162** [comment]
Will be closing unless reproducible.

**Comment by Fontanapink** [comment]
Now it works perfect!

**Comment by michael13162** [comment]
Thanks!
