### ISSUE TITLE
Error while modifying sequence order, from a file downloaded from UtahSymbioHub

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLDesigner#242]
So, I downloaded a SBOL file from my collection in UtahSymbiohub. Saved it to my space so I could edit it and tried to modify the order of some of the sequence. When I tried uploading it back to my collection, the sequence was not uploaded properly (even if it says: Uploaded) because when checking the sequence in UtahSymbioHub, the change in order was not there.

**Comment by michael13162** [comment]
A warning is now shown when attempting to reorder parts that are read-only.  I think this is the problem you encountered (where the part got reordered but the change wasn't actually reflected in the document).

**Comment by cjmyers** [comment]
Looks good.
