### ISSUE TITLE
Create and link to a new SBOLDesigner agent for version 3.0

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#243]
There should be a new agent using by activities for version 3.0 that is uploaded to synbiohub.org.

**Comment by michael13162** [comment]
I've emailed you the new SBOLDesignerAgent and updated the references in ProvenanceUtil.

**Comment by cjmyers** [comment]
Looks good.  I've added it to the SBOLSoftware collection.
