### ISSUE TITLE
Can't close application

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#247]
Prerelease 3.1 on Mac: when I click the red "close" button on the application, it doesn't do anything.  Per the UI semantics of It fixed-window applications, it should quit.

**Comment by cjmyers** [comment]
This one is a duplicate of #201.  This is an issue on Mac that Michael has not been able to sort, in part since he develops on windows.

**Comment by cjmyers** [comment]
Duplicate of #201
