### ISSUE TITLE
Can't remove displayID once set

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#248]
Prerelease 3:

sbol-10204 says that a displayID is optional, but once I set one I cannot remove it. If I delete the contents of the blank, I get an sbol-10204 error telling me it's optional and I've done it wrong.

**Comment by cjmyers** [comment]
It is optional in the specification, but it is required in SBOLDesigner.  Therefore, we should get ahead of the validation error message and report that displayId is required.

**Comment by michael13162** [comment]
The validation error message is now: "The displayId must not be empty."
