### ISSUE TITLE
Can't save over a file

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#249]
I wanted to replace a file I'd been working with earlier with a better version. When I hit "save" and named the file identically, however, it told me it was going to save _into_ the file rather than over it.  And that's exactly what it did.

**Comment by cjmyers** [comment]
Agreed.  We need another option for Overwrite File as well as Overwrite Part and New Version.

**Comment by michael13162** [comment]
An option to overwrite document has been added.  Overwrite part and new version options are still present.  These options will be presented whenever the user tries to save into a document that already exists on disk.

**Comment by cjmyers** [comment]
Looks good though shouldn't Save As also allow for a file to be overwritten?

**Comment by cjmyers** [comment]
Actually, let's call this good for 3.0, and add the overwrite ability to save-as for 3.1

**Comment by michael13162** [comment]
Sounds good to me.

**Comment by jakebeal** [comment]
"You cannot select this file, it already exists"

**Comment by cjmyers** [comment]
Yes, I noticed this too.  It works for Save but not Save-As.  @michael13162 how difficult to make to work for Save-As?

**Comment by michael13162** [comment]
I refactored things so save as now asks the same question when the user chooses to save as into an existing file.  All other paths should be the same.

**Comment by cjmyers** [comment]
Looks good.
