### ISSUE TITLE
Import part

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#25]
Import part should allow selecting a part from a file.

**Comment by cjmyers** [comment]
1) Would be nice to filter the parts to match the roles of the edited component.  If you like to still allow other parts to be selected with different roles, could perhaps had the same two filter role boxes to top of the selection window.

2) When I tried to import the same part for two components, it complains about duplicate parts.  You should first check if the CD is in the factory before trying to copying.  

3) Would be nice for the import directory that you move to be remembered.  This way each time you open import, you don’t need to rebrowse to the directory with parts in it.

**Comment by michael13162** [comment]
All completed.
