### ISSUE TITLE
Do not show warning for Sequence Features (i.e., Role not Component)

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#250]
SequenceAnnotations with Role field by definition are annotating a sequence.  No warning of missing sequence, unless the location does not point to an actual location on the existing sequence.

**Comment by yu-eric** [comment]
This issue has been addressed at #296.

**Comment by SamuelSauce** [comment]
Trying to open a .gb file, specifically (https://github.com/SynBioDex/SBOLTestSuite/blob/master/GenBank/pAGM1467.gb) to test this, but getting an error opening the genbank file. @cjmyers

**Comment by cjmyers** [comment]
No longer a bug
