### ISSUE TITLE
Deprecated SO Term, SO:0001957

### ISSUE THREAD

**Issue by nathanwilk7** [SynBioDex/SBOLDesigner#253]
http://sbolstandard.org/wp-content/uploads/2017/10/SBOLVisual_Specification_2_0_0.pdf, page 45
RNA Stability Element glyph was previously also associated with SO:0001957, but that SO term has
been declared obsolete in Sequence Ontology.
I saved from SBOL designer and got this role for one of the glyphs

**Comment by cjmyers** [comment]
@michael13162 please check all SO term mappings against the SBOLv 2 spec.

**Comment by cjmyers** [comment]
https://github.com/VisBOL/visbol-js/blob/master/lib/soToGlyphType.js

**Comment by michael13162** [comment]
Thanks for reporting this.  I found some issues with SBOLDesigner that I have corrected.  Specifically, the overhangs, CUT, and RNA stability element parts now have correct sequence ontology terms.
