### ISSUE TITLE
Missing 3' restriction enzyme site

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#254]
The 3' restriction enzyme glyph should be a mirror image of the 5' restriction enzyme glyph (cut).

**Comment by cjmyers** [comment]
RES3, RES5 for the names, and change _5OH and _3OH to OH3 and OH5

**Comment by cjmyers** [comment]
Glyph looks good.  I thought we were changing though the names to RES3 and RES5, and same with the _5OH to OH5 and _3OH to OH3.

Also in the tooltip, let's change it to:

5' and 3' rather than Five and Three.

**Comment by SamuelSauce** [comment]
Pushed update.
