### ISSUE TITLE
Unassigned Glyph rendering without role refinement

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#255]
When unassigned glyph is dropped on the schematic with no role refinement, then according to the SBOLv 2 specification, it must be rendered with the Unspecified Glyph (question mark).

**Comment by cjmyers** [comment]
When you select NGA, it should open part editor with part role IDK selected, sequence feature the default role for, and the role refinements should include all descendants of sequence feature.

If the user does not select a role refinement and roles remains sequence feature render as IDK.  Essentially the role for IDK is sequence features.   NGA no longer has a role per se, but its role refinement list should still be all descendants of sequence feature.

NGA only appears on canvas when there is an SO term in the role list, and it is one with no glyph assigned.

The IDK shows up when there is no SO term or the SO term is sequence feature.

BTW: line 109 of Part.java is wrong.  It should not be get(0) instead it should loop the list of roles and find the one from SO.  Must start with: http://identifiers.org/so/

**Comment by cjmyers** [comment]
I've addressed part of this one.  However, these parts remain:

"When you select NGA, it should open part editor with part role IDK selected, sequence feature the default role for, and the role refinements should include all descendants of sequence feature."

"BTW: line 109 of Part.java is wrong. It should not be get(0) instead it should loop the list of roles and find the one from SO. Must start with: http://identifiers.org/so/"

**Comment by cjmyers** [comment]
Change IDK to UNS

**Comment by cjmyers** [comment]
Changing role refinement back to None should change glyph back to IDK.

**Comment by SamuelSauce** [comment]
It appears that I need to edit some code for "Changing role refinement back to None should change glyph back to IDK.", which is on line 700. If roleRefinement is "None" then this if statement is not executed. I tried allowing it to execute if it is "None", but got an exception. I'm a little confused on how the code inside the if statement works. Some insight would be helpful.

**Comment by SamuelSauce** [comment]
That is, line 700 of PartEditDialog.

**Comment by cjmyers** [comment]
I'm not sure if this is the correct place.  I think the change should be in the render code, since when you close the editor with refinement set back to none, it should render as IDK (or what we are changing to UNK).  @michael13162 can you comment?

**Comment by michael13162** [comment]
I think the DesignElement class in SBOLDesign.java has info on each part on the canvas?  Is that what you're asking about?

**Comment by SamuelSauce** [comment]
I'm pretty sure its the section of code at line 700 of PartEditDialog, since this is where the role is set of the part when clicking save, based on what the user had selected, although this section of code does not get executed when selecting "None". Perhaps this could be best discussed in our meeting in the morning.

**Comment by SamuelSauce** [comment]
Hey chris, just double checking on this issue, did we decide it could be closed? If I remember right it appeared to be behaving how you would want it to.

**Comment by cjmyers** [comment]
This part has still not been addressed:

"BTW: line 109 of Part.java is wrong. It should not be get(0) instead it should loop the list of roles and find the one from SO. Must start with: http://identifiers.org/so/"

Also, has IDK been changed to UNS?

**Comment by SamuelSauce** [comment]
Yes IDK has been changed to UNS.

**Comment by SamuelSauce** [comment]
for(int i = 0; i < roles.size(); i++) {
			curr = roles.get(i);
			if(curr)
		}
I've got the following code, but im confused as to where I'm supposed to grab the SO from.

**Comment by cjmyers** [comment]
Check the URI and see if when converted to a string that it starts with: "http://identifiers.org/so/"  This role is the SO role.  You can then test perhaps by hand adding some roles that are not SO URIs.

**Comment by cjmyers** [comment]
Fixed
