### ISSUE TITLE
Update info button

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#26]
Update the info button.  Still points to clarkparsia.

**Comment by michael13162** [comment]
Updated information.  Should I leave Clark & Parsia as authors, or completely replace with Myers Research Group?

**Comment by cjmyers** [comment]
Please see the About for iBioSim.  Let’s have it give the Version, University of Utah and Clark & Parsia on two lines.  Then, add a Credits button with a list of the names of all the developers.  Probably this would be all authors on the IWBDA paper (not the Geneious one but the other one).  

Maybe we could email Michal, John, Evrin, and Bryan to confirm the list.

Chris

**Comment by michael13162** [comment]
I have made the preliminary changes.  Yes, we should confirm names.  Would you like me to send the email?

**Comment by cjmyers** [comment]
Sure.
