### ISSUE TITLE
wasDerivedFrom field for combinatorial expansion

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#261]
When a CombinatorialDerivation is enumerated, it should set the wasDerivedFrom fields to the generated ComponentDefinitions to the CombinatorialDerivation.

**Comment by michael13162** [comment]
The wasDerivedFroms now point back to the original CD (template of the derivation) as well as the derivation itself.

**Comment by cjmyers** [comment]
Looks good closing.
