### ISSUE TITLE
Add wasDerivedFrom to refer to template Component for generated components from a derivation

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#265]
The Components generated when enumerating a CombinatorialDerivation should have their wasDerivedFrom refer to the corresponding template Component.

**Comment by michael13162** [comment]
I was indeed missing this link for the first component of every chain of components for the generated CD.  I've added this now.

**Comment by cjmyers** [comment]
Not closing this one just yet as I'm getting a validation exception.  However, it could be in the validator.  It is a strange one.

**Comment by cjmyers** [comment]
Ok, I officially cannot reproduce the validation error.  Once you enumerate your test cases, please run them through the validator with best practices selected.  Let me know if you see any issues.  If not, we will put this to bed.

**Comment by cjmyers** [comment]
Fixed
