### ISSUE TITLE
Agent should be included in saved files to make them complete

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#274]
The SBOLDesigner Agent should be added to the document when saving an SBOL file to ensure that the SBOLDocument is complete.

**Comment by cjmyers** [comment]
Create an SBOLDesigner 3.1 agent, upload to SBH and publish
Change createProvenance to reference the 3.1 agent
In createProvenance, load local copy of agent into the SBOLDocument

**Comment by SamuelSauce** [comment]
@cjmyers https://synbiohub.utah.edu/user/samuelfbridge/provenance/provenance_collection/1/1f886302f99323ae4d59aa2d945de870020066e0/share 
share link for the provenance i generated.

**Comment by cjmyers** [comment]
Probably should make the new features part of the description describe what is new from 3.0 to 3.1.

**Comment by cjmyers** [comment]
Fixed by PR #388
