### ISSUE TITLE
Using email address as domain name default

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#279]
Rather than asking user for the domain, asking them for their name and email address then use the email address to build a default domain.  They can still change in preferences, but this is a better first time user experience.

**Comment by yu-eric** [comment]
I fixed this and made a pull request at https://github.com/SynBioDex/SBOLDesigner/pull/287.

**Comment by michael13162** [comment]
@cjmyers Does Eric's scheme for creating the uri seem ok to you?

"http://www." + name.toLowerCase().replaceAll("\\s+","") + ".org/"

**Comment by jakebeal** [comment]
I think that this is a bad idea, because it is likely to collide with many real domain names.
Why not put it in the SBOLDesigner namespace?
Something like:
`http://www.async.ece.utah.edu/SBOLDesigner/users/name`+hash-to-avoid-collisions

**Comment by cjmyers** [comment]
Maybe something like:

https://sboldesigner.github.io/user/<encodedEmailAddress>/

**Comment by yu-eric** [comment]
I have changed the URI and added an encoded email in my latest commit.

**Comment by cjmyers** [comment]
Lets just make this only the email address.

**Comment by cjmyers** [comment]
test by removing the preference using XCode and open /Users/<username>/Library/Preferences/edu.utah.ece.plist

**Comment by cjmyers** [comment]
Fixed
