### ISSUE TITLE
Option to use reference the latest version

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#29]
Should double check that all references are using identity and not persisitentIdentity.

Should include an option on the edit part dialog as to whether the part should "Always reference the latest version".  The default should be false.  If checked, the reference to this part should be changed to use the persistentIdentity.

**Comment by michael13162** [comment]
The PartEditDialog gets all the information on its state from the CD that is used to create it.  Therefore, adding a checkbox that controls whether the CD being edited is always the latest version or not would be simple, but having the state of this checkbox persist every time the dialog is used would be difficult.

**Comment by cjmyers** [comment]
The way you could make it persist is to check the Definition for the Component and see if it is using an identity or persistentIdentity.  Namely, when you fetch the CD, you can compare the definition reference to the identity and persistentIdentity to see which one matches.

**Comment by cjmyers** [comment]
No longer relevant
