### ISSUE TITLE
Deletion of features/sequence annotations should not be allowed

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#290]
Currently, sequence annotations/features (for example, when opening a converted genbank file) are viewable in the main canvas.  However, they should not be mutable since we currently don't support that.  As such, deletion/editing/reordering of these sequence features should not be allowed.  It results in undefined behavior (for example, ....nnnnnn.... showing up the parent CD).

**Comment by SamuelSauce** [comment]
Fixed.
