### ISSUE TITLE
Don't allow mixing of CDs and sequence features

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#293]
Right now, when showing sequence features instead of CDs, the user can still drop in CDs.  This doesn't make sense and isn't supported (and causes undefined behavior/other bugs).  The canvas should either be a CD editor or immutable sequence feature viewer.

**Comment by SamuelSauce** [comment]
@cjmyers appears to be fixed. Please verify.

**Comment by cjmyers** [comment]
Agreed.  Closing.
