### ISSUE TITLE
Problem while trying to open different parts of the SBOL document

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLDesigner#306]
I've created a genetic toggle switch. First the LacI Inverter part, then the TetR Inverter part. 
Afterward, I've created a new part, placed two engineered regions, and placed both parts in this new part. I can successfully zoom into the parts, and the LacInverter and TetRinverter are in place. 

But, if I try to click the "Open a part from this document" button, the following error pops-up and then nothing else happens, not letting me open the different parts of the document:

sbol-13206: Best Practice Warning:
The format property of an Attachment SHOULD contain a URI that refers
to a term from the EDAM ontology.
Reference: SBOL Version 2.2.1 Section 7.13 on page 52:
https://synbiohub.programmingbiology.org/public/Cello_Parts/attachment_00009WRPR2gZAT2e0UjRL6/1

**Comment by SamuelSauce** [comment]
I'll see if Pedro can show me on Monday.

-Sam

**Comment by Fontanapink** [comment]
I'll be here.. I mean in the lab
