### ISSUE TITLE
Bug when setting namespace

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#308]
The default namespace being set when a user first starts SBOLDesigner is picking up strange URIs.  This is a serious bug because it can cause illegal URIs especially once uploaded to SynBioHub.

@michael13162 @SamuelSauce can you take a look at this one?

**Comment by SamuelSauce** [comment]
Yes, i'll take a look.

**Comment by cjmyers** [comment]
Please see:

https://github.com/SynBioHub/synbiohub/issues/696

**Comment by SamuelSauce** [comment]
Hey Chris,

Just letting you know that I won't have the opportunity to get to this
issue today as I have had an unexpectedly busy day. Perhaps this weekend,
but surely early next week.

Best,
Sam

**Comment by cjmyers** [comment]
Thanks.

**Comment by cjmyers** [comment]
Cannot reproduce.
