### ISSUE TITLE
When editing displayId, make sure object does not exist

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#33]
When you edit the displayId and try to save the object, should first check if object exists.  If it does, should give the user the option to "Overwrite" or "New Version".  

Note this could work for all edits of a part.  Namely, first edit could save with no prompt, since will not exist, but subsequent ones could give the option to overwrite or new version.

**Comment by michael13162** [comment]
Done.  I also added a settings tab in preferences that controls the default behavior (ask the user, overwrite, or new version).
