### ISSUE TITLE
Don't own part message is confusing

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#330]
Should consider rewording this message or possibly having a preference to indicate whether or not this message should even be given.  Maybe it is fine to simply just update the namespace silently.

**Comment by jakebeal** [comment]
The workflow that I've observed people trying to do is to "just use this part in my design."  If that means implicitly updating the namespace, that seems to be fine.  If there's a way to use the part without updating the namespace, you need to make that easy---and right now, it seems very arbitrary whether SBOLDesigner thinks you're trying to use the part or modify the part.

**Comment by cjmyers** [comment]
Using part does not require namespace change only modify. If message is coming for use then that is a bug. If you know steps that are giving that message in error, that would be useful

Thanks

Chris

**Comment by bbartley** [comment]
My recollection about why this error is so obtrusive is because sometimes I simply want to open a part and inspect its details.  But as soon as I open it, this scary message immediately pops up.  
The user should be able to open a part, inspect its contents, and close the window without issue.  If the user modifies the part, only then should the user be prompted to either import the part to their namespace or to cancel the change.

    On Saturday, November 3, 2018, 9:55:49 PM EDT, cjmyers <notifications@github.com> wrote:  
 
 Using part does not require namespace change only modify. If message is coming for use then that is a bug. If you know steps that are giving that message in error, that would be useful

Thanks

Chris

**Comment by cjmyers** [comment]
That’s a fair point.  It should probably only show up after you make a change.

**Comment by cjmyers** [comment]
This appears to only happen if you open a part that you do not own, then descend into its hierarchy and try to open a part one level down.  Then, you get this message.  To avoid this, we can disable the fields and edit buttons when you do not have edit rights, and add to the top (read-only) on the title, so it is clear that you are view a read-only object.  Have a tooltip that includes the current message about how edit it.

**Comment by jakebeal** [comment]
I don't think this is a good solution, because it thwarts the natural document workflow of "pen a document, start editing, then "save-as".

**Comment by cjmyers** [comment]
I can see your point.  To make sure though we are on the same page, could you try to drop a part, import from registry the sequence and other information, then click on the part and edit.  It should allow you till you click save, at which point it notifies you that you cannot save this part, you don’t own it, and you must save a copy in your own namespace.  Can you confirm that this is the behavior you want?

Now, the tricky case is if you drop a part, import the sequence for the part which has substructure, focus into the part to see the substructure, then try to edit the sub-part.  When you edit this part, you are not allowed to save because you don’t own its parent part.  You currently get a message to this affect even if all you want to do is view its sequence.  Furthermore, to add insult to injury, you can edit the part information, but save is disabled.  The proposed solution was to eliminate the confusing message, make the part editor read-only so you don’t edit and find you cannot save, and allow you to get more information about why it is read-only through a tool tip.  This solution should be fairly easy to implement.

My understanding is you want the first solution above for the second case as well.  This can possibly be done but it is trickier, since you are not just updating the namespace of the part you are looking at and its children, but also the parent part and its reference to child part.  This will be a heavier lift.

**Comment by jakebeal** [comment]
> It should allow you till you click save, at which point it notifies you that you cannot save this part, you don’t own it, and you must save a copy in your own namespace.  Can you confirm that this is the behavior you want?

Yes, this is a good behavior.

The big problem, however, is this: I download an SBOL file (e.g., one of the parts from the iGEM 2016 interlab), open it, and try to drop a part.  At this point, I get the error: 

> Strong_2016Interlab is not owned by you.  Please edit it and/or its parents and choose "yes" to creating an editable copy while re-saving it.

This is where it should just fork the part.

**Comment by cjmyers** [comment]
The example you describe is essentially another instance of "you don't own the parent".  When you open a part you don't own, the canvas is showing you the Components within a part you don't own.  So, when you try to add parts to it, you must first take ownership of the parent part, so you can add components to it.  I agree that the message is very confusing, since it is telling you to edit the parent, so you can take ownership.  What the behavior should be I believe is that it should popup the message you get when you edit with the pencil.  Namely, do you want to take ownership of this part, so you can edit it.  Essentially, in all cases where you try to make changes, it should get permission to take ownership then let you make your edits.

The tricky case though is the one I described earlier, since to edit a sub-part, you must edit its parent (i.e., the CD that references it).  This is tricky since you might have many CDs within the SBOL file that reference  this part.  I don't think you want to update every reference.  I think you only want to update the reference for the part that is currently open with this sub-part.  This can chain up multiple levels though because you could have open a part A, focus into a sub-part B, then focus into sub-part C.  When you edit C, you must also update B and A, but not D which references C but is not part of the design you are currently editing.

**Comment by jakebeal** [comment]
How about giving an option of "update only this reference" or "update all references"?

**Comment by cjmyers** [comment]
Sure.  Seems reasonable.

**Comment by cjmyers** [comment]
updateComponentReferences in SBOLDesign.java needs to first check if CD is in your namespace.  If it is not in your namespace, you need to createCopy to put into your namespace like in confirmEditable, and you need to recursively updateComponentReferences using the parentCDs.  Also if you update the  CD, you need to update parentCDs to include the new CD.

**Comment by cjmyers** [comment]
Sorry, this was a mistake.  It should be confirmEditing in PartEditDialog.  This is the function that brings up the message if you want to edit.  This is a pretty involved issue.  Basically, you need to allow editing of objects outside your namespace but then when Save is pressed, it should update the namespace recursively up the parentCDs.  Currently this is only allowed if you are editing the root CD, the one with no parents.

**Comment by SamuelSauce** [comment]
Okay, I have an idea of where this is going and have made some changes, but probably will need to talk in person about tackling the rest of this, namely the recursive update and copy of all the parents.
