### ISSUE TITLE
Explain why you're asking for contact info on first launch

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#331]
On first launching the current release of SBOLDesigner, it begins by demanding contact information (name and email) in two modal dialogue boxes.  Presumably this is for populating authorship information of parts.

The problem is that this happens before the SBOLDesigner window appears, and since it's without context or explanation it's a) a mysterious stumbling block, and b) possibly even in violation of the GDPR.

This should be changed to:
1. Happen in a single dialogue box
2. Actually explain what program is collecting their information and why, e.g., "Welcome to SBOLDesigner! Please enter your name and email address so that it can be added to the parts that you create to identify you as the author.  If you aren't ready to do so now, you can always do so later through preferences."
3. Add a "later" button that puts in defaults instead.  Anybody who doesn't want to give their info will add bogus stuff anyway, so there's no point in forcing them.

**Comment by cjmyers** [comment]
Good suggestion.  Adding to our priorities.
