### ISSUE TITLE
Improve rendering of sequence features

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#336]
When rendering sequence features, the canvas should show a range of sequence positions and include only those features that are not completely contained within another sequence feature.  Then, when one of the features is focused into, then it should change the range of sequence positions shown and only show those features that are within that range (excluding the one that was selected to focus into), once again not showing any feature that is contained within one being shown.

**Comment by SamuelSauce** [comment]
@cjmyers I believe this was taken care of last year? please check and verify.

**Comment by cjmyers** [comment]
Correct.
