### ISSUE TITLE
Improve rendering of overlapping features

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#337]
When features overlap, need to indicate this in some way.  There are two alternatives that should be considered:

1) Overlap the glyphs of the features that overlap
2) Use a decoration under the overlapping glyphs to indicate that they overlap

**Comment by cjmyers** [comment]
[pSB4A5.zip](https://github.com/SynBioDex/SBOLDesigner/files/2947830/pSB4A5.zip)

**Comment by SamuelSauce** [comment]
Note: use the 'zoom' button to change .setVisible on the buttons to correspond to the current sequence range.

**Comment by cjmyers** [comment]
Add composite indicator when there is sub-features.
