### ISSUE TITLE
Synbiohub is broken

### ISSUE THREAD

**Issue by jurquiza** [SynBioDex/SBOLDesigner#340]
Experiencing problems with pubic and standalone versions

Public 
ngix bad gateway when downloading a collection 
errors when uploading a new collection 

Standalone 
git pull results in a fatal refusing to merge unrelated stories

**Comment by cjmyers** [comment]
Public issue is usually due to having an old Java version.  Which version of Java are you running?

Standalone issue is strange unless you have modified code locally.  You might try cloning to a new directory.
