### ISSUE TITLE
Unable to save edits on parts without version field

### ISSUE THREAD

**Issue by tim-tx** [SynBioDex/SBOLDesigner#343]
I tried to edit a part that I was not the owner of, and got the message:

> The part plasmid_1 is not owned by you and cannot be edited. Do you want to create an editable copy of this part and save your changes?

I say "yes." If I then take some other action like "Load and existing SBOL document" or "Open a part from this document," I get two dialogs in succession:

> Current design has been modified. If you don't save the current design, all your changes will be lost. Do you want to save your changes?

\<Yes>

> This design doesn't have a version, so the previous design will be overwritten. Would you still like to save?

\<Yes>

Then nothing happens. If I try again to open/load/save, I get the same dialogs and nothing afterward.

If I go back to where I generated this file and include a version for each definition as it is created, the issue goes away.

The file I used is here:
[3node.zip](https://github.com/SynBioDex/SBOLDesigner/files/2686487/3node.zip)

**Comment by SamuelSauce** [comment]
This may be caused by another issue relating to editing a part that is not in namespace. I'm getting an indexOutOfBounds exception. I will the indexOutOfBounds then check back to see if this is still an issue.

**Comment by cjmyers** [comment]
This is an issue with libSBOLj which should detect the out-of-range and return null.

**Comment by SamuelSauce** [comment]
Fixed.
