### ISSUE TITLE
Import part only import version 1 of the files

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/SBOLDesigner#344]
I create parts and then upgraded them to new versions but when I import these parts it only import the version 1 no matter if I select version 2 or 3.

**Comment by Gonza10V** [comment]
Step 1: Create a new part, Test1 v1
Step 2: Create a new version of Test1, Test1 v2
Step 3: Create a new SBOL Document, Import part, select Test1, select v2.
Result: The imported part in the new SBOL document is Test1 v1 instead of Test1 v2.

![test1 v1](https://user-images.githubusercontent.com/35148159/51795503-0e135c80-21c3-11e9-99a0-f54e15a1d04e.png)
![test1 v2](https://user-images.githubusercontent.com/35148159/51795504-0eabf300-21c3-11e9-812d-58190e500fac.png)

**Comment by cjmyers** [comment]
Ok, I've reproduced this one.  Here are the steps I took:

1) Click on pencil and change displayId to Test1
2) Drop an RBS onto canvas
3) Edit the RBS and change Name to Test1 with sequence "agct"
    NOTE: at this point I have a part <URI>/Test1/1 that refers to another part <URI>/RBS/1 as a Component
4) Click "Save your current design"
5) Click "Create a new part in this document"
6) Click on pencil and change displayId to Test1
6) Drop an RBS onto canvas
7) Edit the RBS and change Name to Test1 with sequence "tcga"
8) Click "Save your current design"
9) When prompted, select New Version
10) Click "Create a new SBOL document"
11) Click pencil and click "Import part"
12) Select filename that I saved into previously.
13) Select part Test1 Version 2
14) Click on pencil and observe that it loaded Version 1.

Strange.  Thanks for reporting this one.

**Comment by SamuelSauce** [comment]
This issue is not being replicated on my machine. I followed the above steps of creating the SBOL document with version 1 and version 2, with their respective sequences. When I select 'import part', I am given the option of version 1 and 2. When I select either, the correct version is loaded with the correct sequence.

**Comment by cjmyers** [comment]
This appears to be fixed now.
