### ISSUE TITLE
Component of a part without a definition is being dropped

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLDesigner#345]
SBOLDesigner will drop a component if that component doesn't have a ComponentDefinition. When this component is dropped, it doesn't notify the user of it. It would be good if it notifies them if it does.

**Comment by Fontanapink** [comment]
Attached is the file I saw this issue. Try looking at the E1_BetI part to see what I am talking about. 
[circuit_0x41.zip](https://github.com/SynBioDex/SBOLDesigner/files/2774277/circuit_0x41.zip)

If this example is too convoluted, I can summon a simpler one

**Comment by SamuelSauce** [comment]
@cjmyers I think this is fixed as far as I can tell. We can double check tomorrow together.
