### ISSUE TITLE
Compile instructions in README are obsolete

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#347]
The readme gives the following compile instruction:

````
AirBeal:SBOLDesigner jakebeal$ mvn clean install exec:java -Dexec.mainClass="com.clarkparsia.sbol.editor.SBOLDesignerStandalone" && mvn package
````

This fails, however, because `clarkparsia` hasn't had anything to do with this code for quite a while.

**Comment by cjmyers** [comment]
Thanks.  It is updated now.
