### ISSUE TITLE
Delete object outside namespace does not complete after saying yes

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#350]
When you try to delete a component not in your namespace, it asks you if you want to move to your namespace then does not do the actual delete.

**Comment by cjmyers** [comment]
Delete should not need to focus in and change the object namespace of the part being deleted.  Only the parent needs to update.

Similarly, when flipping orientation, should not need to focus in, only the parent namespace needs to be updated. 

Likely, same issue Add, though this is not noticed because the new part is already in the namespace.

**Comment by cjmyers** [comment]
Also, seems Ns are showing up when flip orientation.

**Comment by SamuelSauce** [comment]
I have fixed delete and flipping orientation to only edit the parent namespace. What I have discovered though, is that when flipping a component not in the namespace, the sequence for said component is changed to 'NNNN...N'. I believe that this is occurring because flipOrientation also modifies the sequence annotation to reflect the complementary base pairs of the original sequence. Thus, I believe I need to take over the flipped component into my own namespace. Let me know what you think.

**Comment by cjmyers** [comment]
You shouldn't need to flip the component.  This is done by the getImpliedNucleicAcidSequence.  It is possible that is not working or it is not getting called after the sequenceAnnotation with the flipped annotation has been added.

**Comment by SamuelSauce** [comment]
Yes, I just looked at the ComponentDefinition.class, which is part of the org.sbolstandard.core2 package, and on line 494, it is adding "N" to the returned character array. Not sure why it is doing this, perhaps you do? 
for (int i = 0; i < length; i++) {
	elements += "N";
}

**Comment by cjmyers** [comment]
This function fills in the sequence with N (meaning unknown base).  It then uses the sequence annotations to and the sequences of referenced components to replace these Ns with known sequence values.

The way this could go wrong is if the SequenceAnnotations are not present for all positions when it gets called.  In this case, the sequence parts missing annotations would remain Ns.

**Comment by SamuelSauce** [comment]
I found the problem. On line 512 of ComponentDefinition.class in the org.sbolstandard.core2 package, Sequence.reverseComplement() is called on the flipped sequence. The problem with this method is that it only recognizes lower case letters, thus returning an empty string if it is in caps. This can be demonstrated by flipping any part that has a sequence with all capital letters. Should I leave SBOLDesigner alone and expect a change to be made to Sequence.reverseComplement()? Or do I need to modify SBOLDesigner? Let me know.

**Comment by cjmyers** [comment]
Ah, interesting.  Please log an issue on the libSBOLj github issue tracker.  If you feel like making a pull request on the library, please do that too.

**Comment by SamuelSauce** [comment]
I just created an issue on the tracker. I will make a pull request on the
library sometime tomorrow.
