### ISSUE TITLE
Designs Generated from a Combinatorial Design Need New Sequences

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/SBOLDesigner#360]
Currently, clicking the "Expand the combinatorial design" button generates a set of ComponentDefinitions where each one has the sequence property of the template ComponentDefinition from which it was derived. Instead, each one of these generated ComponentDefinitions should be given a sequence property that refers to a newly generated Sequence object. This generated Sequence object should have an elements property that is the concatenation of the elements from the Sequences of the definitions for the sub-Components of the generated ComponentDefinition (in accordance with the relevant SequenceConstraints that refer to these sub-Components).

**Comment by nroehner** [comment]
Accordingly, the sub-Components of the generated ComponentDefinition should also have SequenceAnnotations that specify their location on the generated Sequence.

**Comment by cjmyers** [comment]
Enumeration seems to have a number of issues.  It not only does not generate correct sequences, but it also does not always generate correct orders.  In the attached example, there is a zero-or-oen promoter and when it is zero, the sequence constraints are lost losing the part order.  See generated instance 222, for example.

[Test.zip](https://github.com/SynBioDex/SBOLDesigner/files/3457174/Test.zip)

**Comment by SamuelSauce** [comment]
Hey Nicholas. I've been taking a look at this issue and I am unable to repeat the error you are getting. The steps I'm following is opening the 'Test.xml' file in SBOLDesigner from the 'Test.zip' listed above. After opening this file I am prompted to chose a design, choosing 'Test'. After opening 'Test' I enumerate the designs, generating a new xml file. After opening this new xml file in SBOLDesigner I find that all of the designs appear to have the correct sequences relating to the enumerated design. Let me know if you get different results and perhaps provide me an exact example where you experience this issue, including all files used.

**Comment by cjmyers** [comment]
This file was generated by me.  However, it would be good if Nic could upload his tests that failed.

**Comment by SamuelSauce** [comment]
This was fixed by PR #367
