### ISSUE TITLE
Add Ability to Specify Whether a Sequence is Generated on Save

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/SBOLDesigner#361]
When saving a ComponentDefinition, the current behavior is to generate a Sequence object with an elements property that is the concatenation of the elements from the Sequences of the definitions for the sub-Components of the saved ComponentDefinition (in accordance with the relevant SequenceConstraints that refer to these sub-Components). This concatenation is performed if any of the sub-Components have a Sequence, even if there is a sub-Component with no Sequence that is located in between other sub-Components that do have Sequences. There should be new a setting under Preferences where a user can specify whether a Sequence is generated on save. There should also be a setting that allows a user to specify that a Sequence should be generated only if all sub-Components have Sequences.

Note that the foregoing settings should also apply to the ComponentDefinitions and Sequences generated by enumeration from a CombinatorialDerivation once #360 is fixed.

**Comment by cjmyers** [comment]
There is already a preference for when the implied sequence gets shorter.  We will change this preference to work whenever the sequence changes at all.  Update the preference description and the ask message when being asked to overwrite/keep.

**Comment by SamuelSauce** [comment]
Fixed

**Comment by cjmyers** [comment]
Need to fix "ask" message

**Comment by cjmyers** [comment]
Message also comes twice for some reason.

**Comment by cjmyers** [comment]
"There should also be a setting that allows a user to specify that a Sequence should be generated only if all sub-Components have Sequences."

**Comment by cjmyers** [comment]
Assume oldSeq and newSeq
change = (oldSeq != newSeq)       
missing = (newSeq generated from Components without a sequence)
if (!change && !missing) // do nothing
else if (!change) // do nothing
else if (!missing) {
   if (OverwriteChange) copy newSeq
   else if (KeepChange) // do nothing
   else if (Ask) { 
        AskChange
        if (yes) copy newSeq
        else // do nothing
else it (missing) {
    if (KeepChange) // do nothing
    else if (OverwriteChange) 
         if (KeepMissing) // do nothing
         else if (OverwriteMissing) copy newSeq
         else if (Ask)
            AskMissing
            if (yes) copy newSeq
            else // do nothing
    else if (AskChange)
         if (KeepMissing) // do nothing
         else if (OverwriteMissing) {
             AskChange
             if (yes) copy newSeq
             else // do nothing
         } else if (AskMissing) {
               AskChangeMissing
             if (yes) copy newSeq
             else // do nothing    
         }

**Comment by SamuelSauce** [comment]
`My logic:
if(changed)
{
	behavior = getSeqBehavior
	if(bavior == !overwrite)
		return; --> dont do anything
	if(missing)
	{
		missingBehavior = getMissingBehavior
		if(missingBehavior == !overwrite)
			return;
	}
	overwriteSequence;//If we got here it means that either:
						Sequence was changed && we want to overwrite if changed && !missing, ||
						Sequence was changred && we want to overwrite && missing && want to overwrite if missing
}`

**Comment by SamuelSauce** [comment]
My logic:

    if(changed)
    {
    	behavior = getSeqBehavior
    	if(bavior == !overwrite)
    		return; --> dont do anything
    	if(missing)
    	{
    		missingBehavior = getMissingBehavior
    		if(missingBehavior == !overwrite)
    			return;
    	}
    	overwriteSequence;//If we got here it means that either:
    						Sequence was changed && we want to overwrite if changed && !missing, ||
    						Sequence was changred && we want to overwrite && missing && want to 
    overwrite if missing
}

**Comment by cjmyers** [comment]
overwrite(missing)
       if (!missing)
           if (askChange) 
              return (Sequence has changed, overwrite?)
          else return overwriteChange
      else 
          if (askChange || askMissing)
             return (Sequence has changed and some components have missing sequences, overwrite?)
         else return (overwriteChange && overwriteMissing)

**Comment by SamuelSauce** [comment]
Should verify that we can close this issue today.

**Comment by cjmyers** [comment]
Fixed by PR #373
