### ISSUE TITLE
Sequence Annotations Needed When Enumerating from a Combinatorial Design

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/SBOLDesigner#362]
Currently, no Sequences are generated when enumerating ComponentDefinitions from a CombinatorialDerivation (see #360). Even when this issue is fixed, in the future the user may indicate with a setting (see #361) that they do not want Sequences generated during enumeration. In both cases, since there is no Sequence, each generated ComponentDefinition needs to include SequenceAnnotations that give its sub-Components GenericLocations with the orientations specified by the corresponding SequenceAnnotations in the template ComponentDefinition.

**Comment by cjmyers** [comment]
Fixed by PR #367
