### ISSUE TITLE
SynBioHub Properties Incorrectly Copied When Enumerating Existing Combinatorial Design

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/SBOLDesigner#363]
When a ComponentDefinition is generated during enumeration from a CombinatorialDerivation and this CombinatorialDerivation is associated with an existing template ComponentDefinition downloaded from SynBioHub, properties such as sbh:ownedBy and sbh:topLevel are incorrectly copied from the template ComponentDefinition to the generated ComponentDefinition.

**Comment by cjmyers** [comment]
@nroehner can you provide more details and a concrete example?

**Comment by cjmyers** [comment]
Enumeration should create blank CDs and fill them in with fixed components and selected variants.

**Comment by cjmyers** [comment]
In createTemplateCopy, it should use createComponentDefinition rather than createCopy to construct the new CD.  

Note that this means that non-varying Components, will need to be "copied" in.

**Comment by cjmyers** [comment]
Fixed by PR #377
