### ISSUE TITLE
Installation Java compatibility

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioDex/SBOLDesigner#365]
Installation instructions state that DNADesigner works with Java8, but it only seems to be compatible with 64-bit Java8. I got it to start on 32-bit using a .bat command to set the memory at 1024
I cobbled one together from the iBioSim install:
@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
REM set DNADesigner=%~dp0..
REM set DDLD_LD_LIBRARY_PATH=%DNADesigner%\lib;%DDLD_LD_LIBRARY_PATH%
REM set PATH=%PATH%;%DNADesigner%
java -Xms1024M -Xms1024M -XX:+UseSerialGC -Djava.library.path="%DNADesigner%\bin" -jar "c:\USERS\GEOFF\DNADesigner\SBOLDesigner.jar"
pause

It's not ideal: I'm not sure if the library commands are needed and I couldn't get the %DNADesigner% path to work so had to type it in long-hand.
Would be great if there could be some description of this on the install instructions and an optional .bat launch for 32-bit Java installations.

**Comment by geoffbaldwin** [comment]
I just pulled the 3.1 version and this seems to run OK on 32-bit Java

**Comment by cjmyers** [comment]
Ok, good.  We mostly test on 64-bit, but good to know.
