### ISSUE TITLE
Updating namespace disconnects CombinatorialDerivations

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#379]
When you update the namespace, all the references to the URI being changed need to be updated including CombinatorialDerivations.

**Comment by cjmyers** [comment]
Consider using rename instead of createCopy in updateComponentReferences as well as other functions that call this function that also call createCopy to move the URI into your namespace.

**Comment by cjmyers** [comment]
Every call of createCopy that changes the namespace should use rename instead to update the references.

**Comment by cjmyers** [comment]
First remove lines loop updating definitions in updateComponentReferences.  Then, note problems with modifications of namespace.  Then, should change all createCopy's in SBOLDesign to rename which should fix these problems.

**Comment by SamuelSauce** [comment]
Fixed. #382
