### ISSUE TITLE
Casting issue

### ISSUE THREAD

**Issue by sarakalvala** [SynBioDex/SBOLDesigner#397]
Hi, when I try to load the built-in parts, I get a message that

 ...dialog.ComponentDefinitionTableModel cannot be cast to ...dialog.TopLevelTablbeModel

and I can't get any further with importing any parts into my design.

Thanks, - Sara
![Screenshot 2024-02-08 at 12 31 18](https://github.com/SynBioDex/SBOLDesigner/assets/15360661/8f472d57-f899-4168-8f53-c629aed75d6d)

**Comment by cjmyers** [comment]
When you are doing import, please be sure to select synbiohub.org rather than the built-in parts.  If this does not work, could provide more detailed instructions of what steps you are doing and where it fails.

**Comment by cjmyers** [comment]
Ok, I reproduced this.  Yes, built-in parts has an issue, but you should be using SynBioHub (https://synbiohub.org)

**Comment by cjmyers** [comment]
This issue is now fixed in the latest release.  However, the built-in parts should still not be used for the assignment.
