### ISSUE TITLE
Built-in Parts

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#40]
com.clarkparsia.sbol.editor has a file called cmyk_parts.rdf.  This might contain the "Built-in parts", which is a feature that should be reimplemented.

**Comment by michael13162** [comment]
Local sbol files can now be added as registries.  Remaining task: get all iGem parts and include as default "built-in parts".

**Comment by michael13162** [comment]
Built-in parts temporarily represented by GeneticToggle.sbol.

**Comment by cjmyers** [comment]
Let’s rename to BuiltInParts.xml 

It can be same content for now though.

Chris

**Comment by michael13162** [comment]
Done.

**Comment by michael13162** [comment]
Swapped with previous BuiltInParts.  We should include a better dataset in the future.  Moving milestone to 2.1.

**Comment by cjmyers** [comment]
Replaced with other issue
