### ISSUE TITLE
Cancel button not closing the SBOL URI prefix window on opening

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#53]
When opening an existing project, an empty SBOL file with the project
name was created. On clicking this SBOL file, a pop-up window appeared
to ask the user to provide a URI prefix for this SBOL file, and the
default was www.dummy.org. The cancel button on this window does not
quit it. This bug, however, only appeared once, and it disappeared in
subsequent tries.

**Comment by michael13162** [comment]
Yup, I already fixed this bug :)

**Comment by cjmyers** [comment]
Except it calls exit which exits iBioSim entirely and not just designer :-(

In any case, I’ve changed iBioSim, so it should never get this question.  It is now taking the URI prefix from the iBioSim preference.  This change is checked in to both designer and iBioSim.
