### ISSUE TITLE
Importing part with annotations

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#54]
When you import a part into your design that has annotations, you can end up with invalid SBOL, since these annotations are in namespaces that are not on your document.  Therefore, when copying an object into your SBOLFactory from an outside source, you should copy in any namespaces that you do not already have in your factory.  You then need to copy these namespaces onto the document you save your design into.

**Comment by michael13162** [comment]
Fixed with updated library.
