### ISSUE TITLE
Add SequenceAnnnotation start and end coordinates to each glyph. 

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SBOLDesigner#62]
Add SequenceAnnnotation start and end coordinates to each glyph. [See this for an example figure that demonstrates this useful convention for visualizing circuit diagrams](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3345007/figure/fig04/)

**Comment by cjmyers** [comment]
Added these to the tool tip.  Maybe this is sufficient for now.
