### ISSUE TITLE
In import part, if the filename provided refers to nonexistent file, then this throws an uncaught exception.

### ISSUE THREAD

**Issue by swapnilb** [SynBioDex/SBOLDesigner#65]

**Comment by cjmyers** [comment]
Can you describe how you did this?  You must select a file from a list in the file browser window, so I'm not sure how you can select a nonexistent file.  Please explain.

**Comment by swapnilb** [comment]
I think I typed in a filename.

**Comment by michael13162** [comment]
![2016-08-24 25](https://cloud.githubusercontent.com/assets/14242505/17951700/2a0c6062-6a32-11e6-8728-b1dd44a4381a.png)

When I tried this, the exception was caught and this error message was shown.  What exactly were the steps you took?  Thanks.

**Comment by cjmyers** [comment]
Cannot reproduce.
