### ISSUE TITLE
Glyphs need to touch backbone

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#66]
To be compatible with SBOL Visual 2.0, the glyphs will need to touch the backbone, so that they can be distinguished from other types of components like proteins.

**Comment by cjmyers** [comment]
Some glyphs currently straddle the line.  Perhaps they need to always be touching the line to be more consistent with a double-strand view.

**Comment by michael13162** [comment]
All glyphs (with the exception of no glyph assigned and primer binding site) now touch the backbone.  Glyphs that straddle the backbone now also cover the backbone.

Note: no glyph assigned is defined as brackets hovering over the backbone, and primer binding site is defined as a check mark hovering over the backbone, so this should be correct.
