### ISSUE TITLE
Add ability to add annotations (url)

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#69]

**Comment by cjmyers** [comment]
Add annotation button to part editor, create an annotation viewer, create an edit annotation window, and a genetic top level viewer.

**Comment by michael13162** [comment]
![7190545802740750457-account_id 1](https://cloud.githubusercontent.com/assets/14242505/17988351/f1072462-6ae2-11e6-8cce-0230dfa94253.jpg)

**Comment by michael13162** [comment]
There is currently a basic viewer.  The source file has some TODOs, but basic viewing functionality is present.  It can stay like this until I finish the other more pressing priority issues.

**Comment by cjmyers** [comment]
Good start.  We can discuss it when we meet.  It is not a priority, but it is still very useful to have.

**Comment by michael13162** [comment]
I've implemented add/remove/edit of Annotations, although I'm handling it all as strings.  This may or may not be correct.

It also needs to be tested more.

**Comment by cjmyers** [comment]
String and URL annotations are different, but I’m not sure that we are really handling int/double/boolean annotations differently.  So, string and URL may be the only types you need to worry about.

Chris

**Comment by michael13162** [comment]
URIs are now clickable!

**Comment by michael13162** [comment]
And addition of new clickable URIs is now supported.  With that, basic annotation support should be complete.

**Comment by cjmyers** [comment]
Just curious.  Is the “Clickable” word needed to make this work for some reason?

**Comment by michael13162** [comment]
No, (besides being terrible software engineering haha) I just added that because I was having a hard time getting the links to show up differently than the normal String in the table.  I can replace it with something else.  If you want, I could also spend more time trying to make them appear different, like italics or something.

**Comment by cjmyers** [comment]
I think it is okay to remove it and not worry about it looking different.  It can be a hidden feature :-)

**Comment by michael13162** [comment]
Cool, I've removed it.
