### ISSUE TITLE
Generic Part should allow any SO from SequenceFeature branch

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#72]
Genetic Part should allow any role refinement derived from SequenceFeature.

**Comment by cjmyers** [comment]
Default Refinement Role to Engineered Region when added in the schematic, but when read from file, should be what is in the file.

**Comment by michael13162** [comment]
Gen part is SO type sequence feature, but when dropped into canvas by user, it should be engineered region.

**Comment by michael13162** [comment]
By default, Gen part's role is sequence feature now.  However, if the user drops the part onto the canvas, it has a refinement role of engineered region.  This allows for other refinement roles to be possible when opening external designs.
