### ISSUE TITLE
Add wasDerivedFrom clickable link to PartEditor

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#79]
If a part is imported from SBOLStack/is iGEM part, add clickable link to a wasDerivedFrom field in the part editor.

**Comment by michael13162** [comment]
If wasDerivedFrom is set, displays a clickable link.  Also made version and wasDerivedFrom optional PartEditDialog fields to reduce clutter.

**Comment by michael13162** [comment]
Needs further testing.

**Comment by cjmyers** [comment]
This is great.  Works well.

Chris
