### ISSUE TITLE
Null pointer exception when no name/email specified

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#81]
The name/email info when not set causes an exception in setURIprefix() in SBOLDesignerPlugin.java.  I've added a null pointer check, but I'm not sure if this will later cause other problems.  Needs to be checked.

**Comment by cjmyers** [comment]
Dealt with maybe but need to test by wiping preferences and running first in iBioSim.

**Comment by michael13162** [comment]
Was unable to reproduce.
