### ISSUE TITLE
Cache parts for browsing

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#86]
It's very slow (often several seconds) to load a large parts list like SBOL stack.
Rather than retrieving each time, you should be using a cache.
You can check for updates in the background.

Likewise, you shouldn't load all of the elements before you start running: load the first screenful and then load the rest in the background after the interface has already become responsive.

**Comment by michael13162** [comment]
I will work on caching and multithreading.

**Comment by michael13162** [comment]
The operation is now multithreaded and has a cool loading icon :)
