### ISSUE TITLE
Flashlight icon unintuitive

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#87]
My natural inclination for adding attaching parts to constructs in the diagram was to double-click on the diagram.  The dialog that comes up there should have some way of getting you into part-adding mode.

I only found the flashlight icon after Chris told me about it - before that I was totally lost.

**Comment by michael13162** [comment]
I will change the icon to a magnifying glass.

**Comment by michael13162** [comment]
The flashlight icon has been replaced by a magnifying glass and there is now a button in the part editor labeled "import registry part" which lets you browse the registries and select a part to import.
