### ISSUE TITLE
SBOL Stack Integration

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#9]
Rewrite SelectPartDialog using SBOL Stack java frontend.

**Comment by michael13162** [comment]
There is currently no way to insert TopLevels that aren't already in an SBOLDocument (independent) into another SBOLDocument.  This makes integrating with the SBOL Stack frontend annoying because some of their methods return independent TopLevels, which therefore can't be used.

**Comment by cjmyers** [comment]
CreateCopy should work.  

Chris

**Comment by michael13162** [comment]
I see.  My mistake.

**Comment by michael13162** [comment]
Fails when importing the same CD multiple times due to URI uniqueness issues.  Also, roles are getting messed up.

**Comment by michael13162** [comment]
Pull out the SO role using SO.getID().  Then, use isDecendentOf() to find which image to use.

**Comment by michael13162** [comment]
Have way to upload parts.

**Comment by michael13162** [comment]
Upload feature added.  Version from ComponentMetadata is a separate issue.
