### ISSUE TITLE
Stack querying needs to deal with SO term's descendants

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#91]

**Comment by michael13162** [comment]
@udp Has this been updated on your end?

**Comment by cjmyers** [comment]
I've added an issue to the SynBioHub tracker, but I just realized that you also do these searches in files.  How is this done?  For this, we cannot rely on SynBioHub, instead, we will need to use the SequenceOntology functionality in libSBOLj to filter.

**Comment by michael13162** [comment]
SBOLUtils.getCDOfRole() returns all CDs whose role is or is a descendent of the query role.  This should handle local files correctly.  Is SynBioHub now doing this correctly as well?  If so, you can close this issue.

**Comment by cjmyers** [comment]
This is not in place yet, but Zach and James think it is doable within SynBioHub.  So, I guess this is now a synbiohub issue and can be closed here.
