### ISSUE TITLE
Stack querying should take role refinement into account

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#92]

**Comment by cjmyers** [comment]
Either need a new way to query an OR relationships over the set of Roles, or need to do several queries for a Role and all its descendants.

**Comment by michael13162** [comment]
This should work now.

**Comment by udp** [comment]
Please can you make a new GitHub release?

I was demoing Designer today and couldn't find a jar for the latest version.

Sent from my iPhone

On Dec 8, 2016, at 19:53, Michael Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:


This should work now.

-

**Comment by cjmyers** [comment]
We may not want an official release quite yet, so I’ve added a SNAPSHOT jar to github.  It is called SBOLDesigner-2.2-SNAPSHOT.jar 

James: please grab this one and confirm that it works for you.

Chris
