### ISSUE TITLE
Validate all rules including best practice on open

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#96]
When you open a part, check it against all validation rules including best practice.  Report errors to the user and warn them buyer beware.

**Comment by michael13162** [comment]
Is this done by SBOLReader.setCompliant(true)?  If so, then this is already the case.  However, I added a check for the document to load just in case.

**Comment by cjmyers** [comment]
No, this only checks compliant URIs.  If you want to check best practices, this must be done only after reading.  This can be done using the validateSBOL method in SBOLValidate.java.  Note the bestPractice flag.

**Comment by michael13162** [comment]
Thanks.  I wasn't sure where to find that method.  I've updated it to use SBOLValidate now.
