### ISSUE TITLE
Representing circular DNA

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#97]
Right now dropping an Origin of Replication makes a DNA circular.  Instead, should read the type field to see if it should be circular.  One cannot rely on the presence of a unique Origin of Replication object always being present.  There can be none or more than one.  

This also means that the Origin of Replication should be able to appear anywhere that a part appears not just in the bottom half of a circular construct.  Indeed, a division of parts upon the top and bottom part of a circular construct would make a better use of schematic real estate.

**Comment by michael13162** [comment]
What constitutes a circular type?  Currently, we support "DNA, Complex, Effector, Protein, RNA, Small_molecule".

**Comment by michael13162** [comment]
libSBOLj has type circular in SequenceOntology class.

**Comment by michael13162** [comment]
Ori is now not tied to drawing of the circular backbone.  However, I'm having a hard time getting the backbone to show up without a part sitting on it.  After digging around the code for quite a bit, I'm still unsure how everything fits together. 

I will try to make a pseudo part that represents "circular" and adding that to the backbone box to see if it gets the circular backbone to show up.

**Comment by michael13162** [comment]
Should go back to using a part to represent circular.  Part could be called "plasmid backbone/vector".  Ori would just be another normal part.  This part should add circular type to canvas CD.

**Comment by michael13162** [comment]
This should work now.  I used 	public static final Part CIRCULAR = createPart("Circular Backbone", "Circular", "blank-backbone.png",
			ImageType.CENTERED_ON_BASELINE, "SO:0000755");

as the new part.  However, this might not be the correct SO term.

**Comment by cjmyers** [comment]
Done
